	strHtml = '<div id="footer">';
		strHtml = strHtml + '<div class="footer_nav">';
			strHtml = strHtml + '<ul>';
				strHtml = strHtml + '<li class="first"><a href="http://company.lottemart.com/company/company.jsp" target="_blank">회사소개</a></li>';
				strHtml = strHtml + '<li><a href="#" onclick="javascript:window.open(\'/front/footer/personalInfoPop.do\',\'pop\',\'width=640,height=560,top=50,left=50,scrollbars=no,resizable=no\')" >개인정보취급방침</a></li>';
				strHtml = strHtml + '<li><a href="#" onclick="javascript:window.open(\'/front/footer/corpProvPop.do\',\'pop\',\'width=640,height=500,top=50,left=50,scrollbars=yes,resizable=no\')">법인사업자 이용약관</a></li>';
				strHtml = strHtml + '<li><a href="#" onclick="javascript:window.open(\'/front/footer/personalProvPop.do\',\'pop\',\'width=640,height=500,top=50,left=50,scrollbars=yes,resizable=no\')">개인사업자 이용약관</a></li>';
			strHtml = strHtml + '</ul>';
			strHtml = strHtml + '<!-- 관계사 사이트 바로가기 -->';
			strHtml = strHtml + '<div class="relative_site">';
			strHtml = strHtml + '<select style="width:170px;" onchange="if(this.value) window.open(this.value);">';
			strHtml = strHtml + '<option value="">관계사 사이트 바로가기</option>';
			strHtml = strHtml + '<option value="http://www.lotte.co.kr">롯데그룹</option>';
			strHtml = strHtml + '<option value="http://www.lottetown.com">롯데타운</option>';
			strHtml = strHtml + '<option value="http://www.lottemembers.com/">롯데멤버스</option>';
			strHtml = strHtml + '<option value="http://green.lotte.co.kr">롯데환경경영</option>';
			strHtml = strHtml + '<option value="http://www.daehong.com">대홍기획</option>';
			strHtml = strHtml + '<option value="http://www.lottecon.co.kr">롯데건설</option>';
			strHtml = strHtml + '<option value="http://www.lotteapt.net">- 롯데캐슬</option>';
			strHtml = strHtml + '<option value="http://www.lottelem.co.kr">롯데기공</option>';
			strHtml = strHtml + '<option value="http://www.lotte.com">롯데닷컴</option>';
			strHtml = strHtml + '<option value="http://www.llc.co.kr">롯데로지스틱스</option>';
			strHtml = strHtml + '<option value="http://www.lotteria.co.kr">롯데리아</option>';
			strHtml = strHtml + '<option value="http://www.lotteriamall.com">- 롯데리아몰</option>';
			strHtml = strHtml + '<option value="http://www.angelinus.co.kr">엔제리너스</option>';
			strHtml = strHtml + '<option value="http://shop.angelinus.co.kr">- 엔제리너스몰</option>';
			strHtml = strHtml + '<option value="http://www.lottemart.com">롯데마트</option>';
			strHtml = strHtml + '<option value="http://company.lottemart.com">- 롯데마트 홍보</option>';
			strHtml = strHtml + '<option value="http://kr.lottedfs.com">롯데면세점</option>';
			strHtml = strHtml + '<option value="http://www.lottedfs.com">롯데인터넷면세점</option>';
			strHtml = strHtml + '<option value="http://www.busanlottedfs.com">부산롯데인터넷면세점</option>';
			strHtml = strHtml + '<option value="http://www.lottecorp.com">롯데물산</option>';
			strHtml = strHtml + '<option value="http://www.lotteshopping.com/">롯데백화점</option>';
			strHtml = strHtml + '<option value="http://www.lotteoutlets.com">- 롯데아울렛</option>';
			strHtml = strHtml + '<option value="http://www.lotteshopping.com/green/index.jsp">- 롯데그린파트너십</option>';
			strHtml = strHtml + '<option value="http://buying.lotteshopping.com">- 상품본부</option>';
			strHtml = strHtml + '<option value="http://lotteedi.dpt.co.kr">- EDI 시스템</option>';
			strHtml = strHtml + '<option value="http://www.eshoppingb2b.com">- B2B 구매시스템</option>';
			strHtml = strHtml + '<option value="http://www.lotteb.co.kr">롯데브랑제리</option>';
			strHtml = strHtml + '<option value="http://www.skyhill.co.kr">롯데스카이힐 C.C.</option>';
			strHtml = strHtml + '<option value="http://www.lottesamkang.com">롯데삼강</option>';
			strHtml = strHtml + '<option value="http://www.lotteins.co.kr">롯데손해보험</option>';
			strHtml = strHtml + '<option value="http://www.3655.co.kr">- 롯데하우머치</option>';
			strHtml = strHtml + '<option value="http://www.lotteintl.co.kr">롯데상사</option>';
			strHtml = strHtml + '<option value="http://www.lottesuper.co.kr">롯데슈퍼</option>';
			strHtml = strHtml + '<option value="http://www.lottecinema.co.kr">롯데시네마</option>';
			strHtml = strHtml + '<option value="http://www.lottefood.co.kr">롯데식품</option>';
			strHtml = strHtml + '<option value="http://www.lotteasahi.co.kr">롯데아사히주류</option>';
			strHtml = strHtml + '<option value="http://www.lotteal.co.kr">롯데알미늄</option>';
			strHtml = strHtml + '<option value="http://www.lotteelife.co.kr">- 롯데이라이프</option>';
			strHtml = strHtml + '<option value="http://www.lotteacademy.co.kr">롯데인재개발원</option>';
			strHtml = strHtml + '<option value="http://edu.lotteacademy.co.kr">-사이버인재개발원</option>';
			strHtml = strHtml + '<option value="http://www.lotteworld.com">롯데월드</option>';
			strHtml = strHtml + '<option value="http://www.lottelhp.com">롯데유통사업본부</option>';
			strHtml = strHtml + '<option value="http://www.giantsclub.com">롯데자이언츠</option>';
			strHtml = strHtml + '<option value="http://www.lottefoundation.or.kr">롯데재단</option>';
			strHtml = strHtml + '<option value="http://www.ldcc.co.kr">롯데정보통신</option>';
			strHtml = strHtml + '<option value="http://www.lotteconf.co.kr">롯데제과</option>';
			strHtml = strHtml + '<option value="http://www.lottehealth1.com">- 헬스원</option>';
			strHtml = strHtml + '<option value="http://www.natuur.co.kr">- 나뚜루</option>';
			strHtml = strHtml + '<option value="http://www.pepero.co.kr">- 빼빼로</option>';
			strHtml = strHtml + '<option value="http://www.cheetos.co.kr">- 치토스</option>';
			strHtml = strHtml + '<option value="http://www.lottepharm.co.kr">롯데제약</option>';
			strHtml = strHtml + '<option value="http://www.lottejtb.com">롯데제이티비</option>';
			strHtml = strHtml + '<option value="http://www.lotteliquor.com">롯데주류BG</option>';
			strHtml = strHtml + '<option value="http://www.lotternd.com">롯데중앙연구소</option>';
			strHtml = strHtml + '<option value="http://job.lotte.co.kr">롯데채용센터</option>';
			strHtml = strHtml + '<option value="http://www.lottechilsung.co.kr">롯데칠성음료</option>';
			strHtml = strHtml + '<option value="http://www.coffeecantata.co.kr">- 칸타타</option>';
			strHtml = strHtml + '<option value="http://company.lottechilsung.co.kr">- 롯데칠성음료 기업</option>';
			strHtml = strHtml + '<option value="http://www.lottecard.co.kr">롯데카드</option>';
			strHtml = strHtml + '<option value="http://www.lottecap.com">롯데캐피탈</option>';
			strHtml = strHtml + '<option value="http://www.lotteham.co.kr">롯데햄</option>';
			strHtml = strHtml + '<option value="http://www.lottehotel.com">롯데호텔</option>';
			strHtml = strHtml + '<option value="http://www.lottehotelbusan.com">부산롯데호텔</option>';
			strHtml = strHtml + '<option value="http://www.lotteimall.com/main/Index.jsp">롯데홈쇼핑</option>';
			strHtml = strHtml + '<option value="http://www.freshdelica.co.kr">롯데후레쉬델리카</option>';
			strHtml = strHtml + '<option value="http://www.charlottetheater.co.kr">샤롯데씨어터</option>';
			strHtml = strHtml + '<option value="http://www.avenuel.co.kr">에비뉴엘</option>';
			strHtml = strHtml + '<option value="http://www.wellga.com">웰가</option>';
			strHtml = strHtml + '<option value="http://www.uniqlo.kr">유니클로</option>';
			strHtml = strHtml + '<option value="http://www.canon-bs.co.kr">캐논코리아비즈니스솔루션</option>';
			strHtml = strHtml + '<option value="http://www.kpchem.co.kr">케이피케미칼</option>';
			strHtml = strHtml + '<option value="http://www.7-eleven.co.kr">코리아세븐</option>';
			strHtml = strHtml + '<option value="http://www.krispykreme.co.kr">크리스피크림도넛</option>';
			strHtml = strHtml + '<option value="http://www.toysrus.co.kr">토이저러스</option>';
			strHtml = strHtml + '<option value="http://www.fujifilm.co.kr">한국후지필름</option>';
			strHtml = strHtml + '<option value="http://shop.fujifilm.co.kr">- 후지필름 쇼핑몰</option>';
			strHtml = strHtml + '<option value="http://www.hpc.co.kr">호남석유화학</option>';
			strHtml = strHtml + '<option value="http://www.tgif.co.kr">T.G.I.Friday&apos;s</option>';
			strHtml = strHtml + '<option value="http://www.kirin.co.kr">기린식품</option>';
			strHtml = strHtml + '<option value="http://www.mybi.co.kr">마이비</option>';
			strHtml = strHtml + '<option value="http://www.hanpay.net">한페이시스</option>';
			strHtml = strHtml + '<option value="http://www.lottestyle.co.jp">롯데스타일</option>';
		strHtml = strHtml + '</select>';
			strHtml = strHtml + '</div>';
			strHtml = strHtml + '<!-- //관계사 사이트 바로가기 -->';
		strHtml = strHtml + '</div>';
		strHtml = strHtml + '<div class="footer_cont">';
			strHtml = strHtml + '<p class="logo"><a href="#" target="_blank"><img src="'+_imgUrl+'/bb/front/common/footer-logo.gif" alt="LOTTE MART B2B"></a></p>';
			strHtml = strHtml + '<div class="addr_wrap">';
			strHtml = strHtml + '<address>';
            strHtml = strHtml + '롯데쇼핑㈜ 롯데마트사업본부 대표이사 : 이철우, 서울시 송파구 신천동 7 -18 번지 롯데캐슬플라자 6층<br>';
            strHtml = strHtml + 'TEL. <span class="ls0">1577-2500</span> , 사업자등록번호 : <span class="ls0">215-85-13569</span>, 통신판매업 신고 : 송파 제<span class="ls0">3366</span>호,<br>';
            strHtml = strHtml + '개인정보 관리책임 및 청소년보호 책임자 : 박창규 고객정보팀장, <span class="ls0"><a href="mailto:webmarster@lottemart.com">webmarster@lottemart.com</a></span>';
			strHtml = strHtml + '</address>';
			strHtml = strHtml + '<p><img src="'+_imgUrl+'/bb/front/common/img-copyright.gif" alt="Copyright 2011 LOTTEMART. All rights reserved."></p>';
			strHtml = strHtml + '</div>';
			strHtml = strHtml + '<ul class="adv">';
				strHtml = strHtml + '<li class="first"><a href="http://www.lotteshoppingir.com/" target="_blank"><img src="'+_imgUrl+'/bb/front/common/img-lotteshoppingir.gif" alt="LOTTE SHOPPING IR"></a></li>';
				strHtml = strHtml + '<li><a href="http://www.visitkoreayear.com/korea/main/main.asp" target="_blank"><img src="'+_imgUrl+'/bb/front/common/img-visitkoreayear.gif" alt="KOREA 2010-2012 한국방문의 해"></a></li>';
			strHtml = strHtml + '</ul>';
		strHtml = strHtml + '</div>';
	strHtml = strHtml + '</div>';

document.write(strHtml);