document.write("					<div id='digi_lnb'>");
document.write("						<ul>");
document.write("							<li class='d1'>");
document.write("								<a href='javascript:goCategorySpecList(\"C0210001\");' class='d1'><img src='//simage.lottemart.com/images/contentimg/special/digi-lnb-01-off.gif' alt='디지털카메라'></a>");
document.write("								<div id='display_1' class='digi_display' style='display:none;'><div class='con'>");
document.write("									<div class='col1'>");
document.write("										<h4>");
document.write("											<a href='javascript:goCategorySpecList(\"C02100010001\");'>카메라</a>");
document.write("										</h4>");
document.write("										<ul>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000100010001\");'>DSLR카메라</a></li>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000100010002\");'>컴팩트카메라</a></li>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000100010003\");'>하이브리드카메라</a></li>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000100010004\");'>인스탁스/토이카메라</a></li>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000100010005\");'>캠코더</a></li>");
document.write("										</ul>");
document.write("									</div>");
document.write("									<div class='col2'>");
document.write("										<h4>");
document.write("											<a href='javascript:goCategorySpecList(\"C02100010002\");'>카메라/캠코더 악세서리</a>");
document.write("										</h4>");
document.write("										<ul>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000100020001\");'>삼각대</a></li>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000100020002\");'>가방</a></li>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000100020003\");'>SD/CF메모리카드</a></li>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000100020004\");'>플래쉬</a></li>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000100020005\");'>렌즈</a></li>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000100020006\");'>카메라소품</a></li>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000100020007\");'>쌍안경/망원경</a></li>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000100020008\");'>캠코더소품</a></li>");
document.write("										</ul>");
document.write("									</div>");
document.write("								</div></div>");
document.write("							</li>");
document.write("							<li class='d1'>");
document.write("								<a href='javascript:goCategorySpecList(\"C0210002\");'><img src='//simage.lottemart.com/images/contentimg/special/digi-lnb-02-off.gif' alt='컴퓨터/주변기기'></a>");
document.write("								<div id='display_2' class='digi_display' style='display:none;'><div class='con'>");
document.write("									<div class='col1'>");
document.write("										<h4>");
document.write("											<a href='javascript:goCategorySpecList(\"C02100020001\");'>컴퓨터</a>");
document.write("										</h4>");
document.write("										<ul>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000200010001\");'>데스크탑/일체형PC</a></li>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000200010002\");'>노트북</a></li>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000200010003\");'>태블릿 PC</a></li>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000200010004\");'>모니터</a></li>");
document.write("										</ul>");
document.write("									</div>");
document.write("									<div class='col2'>");
document.write("										<h4>");
document.write("											<a href='javascript:goCategorySpecList(\"C02100020002\");'>컴퓨터주변기기</a>");
document.write("										</h4>");
document.write("										<ul>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000200020001\");'>유선키보드</a></li>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000200020002\");'>무선키보드</a></li>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000200020003\");'>유선마우스</a></li>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000200020004\");'>무선마우스</a></li>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000200020005\");'>블루투스마우스</a></li>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000200020006\");'>스피커/도킹스피커</a></li>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000200020007\");'>프린터/복합기</a></li>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000200020008\");'>공CD</a></li>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000200020009\");'>USB</a></li>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000200020010\");'>외장하드</a></li>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000200020011\");'>공유기/랜카드</a></li>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000200020012\");'>헤드셋</a></li>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000200020013\");'>카드리더기/허브</a></li>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000200020014\");'>잉크</a></li>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000200020015\");'>토너</a></li>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000200020016\");'>각종케이블/멀티탭</a></li>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000200020017\");'>노트북가방/소품</a></li>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000200020018\");'>마우스패드</a></li>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000200020019\");'>화상카메라</a></li>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000200020020\");'>보안기</a></li>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000200020021\");'>컴퓨터소품</a></li>");
document.write("										</ul>");
document.write("									</div>");
document.write("								</div></div>");
document.write("							</li>");
document.write("							<li class='d1'>");
document.write("								<a href='javascript:goCategorySpecList(\"C0210003\");'><img src='//simage.lottemart.com/images/contentimg/special/digi-lnb-03-off.gif' alt='네비게이션/MP3'></a>");
document.write("								<div id='display_3' class='digi_display' style='display:none;'><div class='con'>");
document.write("									<div class='col1'>");
document.write("										<h4>");
document.write("											<a href='javascript:goCategorySpecList(\"C02100030001\");'>네비게이션/하이패스</a>");
document.write("										</h4>");
document.write("										<ul>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000300010001\");'>네비게이션</a></li>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000300010002\");'>하이패스/블랙박스</a></li>");
document.write("										</ul>");
document.write("									</div>");
document.write("									<div class='col2'>");
document.write("										<h4>");
document.write("											<a href='javascript:goCategorySpecList(\"C02100030002\");'>MP3/PMP/전자사전</a>");
document.write("										</h4>");
document.write("										<ul>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000300020001\");'>MP3</a></li>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000300020002\");'>PMP</a></li>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000300020003\");'>어학학습기/전자사전</a></li>");
document.write("										</ul>");
document.write("");
document.write("										<h4 class='r2'>");
document.write("											<a href='javascript:goCategorySpecList(\"C02100030003\");'>음향가전</a>");
document.write("										</h4>");
document.write("										<ul>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000300030001\");'>라디오/녹음기</a></li>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000300030002\");'>이어폰</a></li>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000300030003\");'>헤드폰</a></li>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000300030004\");'>블루투스</a></li>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000300030005\");'>오디오/카세트</a></li>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000300030006\");'>전자악기</a></li>");
document.write("										</ul>");
document.write("									</div>");
document.write("								</div></div>");
document.write("							</li>");
document.write("							<li class='d1'>");
document.write("								<a href='javascript:goCategorySpecList(\"C0210004\");'><img src='//simage.lottemart.com/images/contentimg/special/digi-lnb-04-off.gif' alt='스마트폰 악세서리'></a>");
document.write("								<div id='display_4' class='digi_display' style='display:none;'><div class='con'>");
document.write("									<div class='col1'>");
document.write("										<h4>");
document.write("											<a href='javascript:goCategorySpecList(\"C02100040001\");'>갤럭시탭</a>");
document.write("										</h4>");
document.write("										<ul>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000400010002\");'>갤럭시탭 케이스</a></li>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000400010003\");'>갤럭시탭 보호필름</a></li>");
document.write("										</ul>");
document.write("");
document.write("										<h4 class='r2'>");
document.write("											<a href='javascript:goCategorySpecList(\"C02100040002\");'>아이패드</a>");
document.write("										</h4>");
document.write("										<ul>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000400020002\");'>아이패드 케이스</a></li>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000400020003\");'>아이패드보호필름</a></li>");
document.write("										</ul>");
document.write("");
document.write("										<h4 class='r2'>");
document.write("											<a href='javascript:goCategorySpecList(\"C02100040003\");'>갤럭시S</a>");
document.write("										</h4>");
document.write("										<ul>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000400030002\");'>갤럭시S케이스</a></li>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000400030003\");'>갤럭시S보호필름</a></li>");
document.write("										</ul>");
document.write("");
document.write("										<h4 class='r2'>");
document.write("											<a href='javascript:goCategorySpecList(\"C02100040004\");'>아이폰</a>");
document.write("										</h4>");
document.write("										<ul>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000400040002\");'>아이폰 케이스</a></li>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000400040003\");'>아이폰 보호필름</a></li>");
document.write("										</ul>");
document.write("									</div>");
document.write("									<div class='col2'>");
document.write("										<h4>");
document.write("											<a href='javascript:goCategorySpecList(\"C02100040005\");'>기타휴대폰</a>");
document.write("										</h4>");
document.write("										<ul>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000400050002\");'>휴대폰케이스</a></li>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000400050003\");'>휴대폰보호필름</a></li>");
document.write("										</ul>");
document.write("");
document.write("										<h4 class='r2'>");
document.write("											<a href='javascript:goCategorySpecList(\"C02100040006\");'>스트랩/블루투스/기타</a>");
document.write("										</h4>");
document.write("										<ul>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000400060001\");'>스트랩</a></li>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000400060002\");'>블루투스</a></li>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000400060003\");'>도킹</a></li>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000400060004\");'>거치대/악세서리</a></li>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000400060005\");'>키보드/기타</a></li>");
document.write("										</ul>");
document.write("");
document.write("										<h4 class='r2'>");
document.write("											<a href='javascript:goCategorySpecList(\"C02100040007\");'>이어폰/충전기</a>");
document.write("										</h4>");
document.write("										<ul>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000400070001\");'>이어폰</a></li>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000400070002\");'>헤드폰</a></li>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000400070003\");'>충전기/케이블</a></li>");
document.write("										</ul>");
document.write("									</div>");
document.write("								</div></div>");
document.write("							</li>");
document.write("							<li class='d1'>");
document.write("								<a href='javascript:goCategorySpecList(\"C0210005\");'><img src='//simage.lottemart.com/images/contentimg/special/digi-lnb-05-off.gif' alt='주방/생활/계절가전'></a>");
document.write("								<div id='display_5' class='digi_display' style='display:none;'><div class='con'>");
document.write("									<div class='col1'>");
document.write("										<h4>");
document.write("											<a href='javascript:goCategorySpecList(\"C02100050001\");'>생활가전</a>");
document.write("										</h4>");
document.write("										<ul>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000500010001\");'>공기청정기</a></li>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000500010002\");'>청소기</a></li>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000500010003\");'>다리미/미싱</a></li>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000500010004\");'>드라이어/고데기</a></li>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000500010005\");'>피부미용/소형가전</a></li>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000500010006\");'>전기면도기</a></li>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000500010007\");'>전기면도기/악세서리</a></li>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000500010008\");'>체온계/전동칫솔/전자담배</a></li>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000500010009\");'>유선/유무선전화기</a></li>");
document.write("										</ul>");
document.write("									</div>");
document.write("									<div class='col2'>");
document.write("										<h4>");
document.write("											<a href='javascript:goCategorySpecList(\"C02100050002\");'>주방가전</a>");
document.write("										</h4>");
document.write("										<ul>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000500020001\");'>밥솥</a></li>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000500020002\");'>IH압력밥솥</a></li>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000500020003\");'>토스터기</a></li>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000500020004\");'>약탕/녹즙기</a></li>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000500020005\");'>커피메이커</a></li>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000500020006\");'>주전자</a></li>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000500020007\");'>믹서기</a></li>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000500020008\");'>제빵기/쿠커</a></li>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000500020009\");'>전기팬/그릴</a></li>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000500020010\");'>전자레인지</a></li>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000500020011\");'>가스/오븐레인지</a></li>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000500020012\");'>건조기/식기세척기</a></li>");
document.write("										</ul>");
document.write("									</div>");
document.write("									<div class='col3'>");
document.write("										<h4>");
document.write("											<a href='javascript:goCategorySpecList(\"C02100050003\");'>냉방가전</a>");
document.write("										</h4>");
document.write("										<ul>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000500030001\");'>에어컨</a></li>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000500030002\");'>선풍기</a></li>");
document.write("										</ul>");
document.write("");
document.write("										<h4 class='r2'>");
document.write("											<a href='javascript:goCategorySpecList(\"C02100050004\");'>난방가전</a>");
document.write("										</h4>");
document.write("										<ul>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000500040001\");'>히터기</a></li>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000500040002\");'>전기요</a></li>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000500040003\");'>전기장판</a></li>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000500040004\");'>전기매트</a></li>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000500040005\");'>가습기</a></li>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000500040006\");'>에어워셔</a></li>");
document.write("										</ul>");
document.write("									</div>");
document.write("									<div class='col3'>");
document.write("										<h4>");
document.write("											<a href='javascript:goCategorySpecList(\"C02100050005\");'>건강가전</a>");
document.write("										</h4>");
document.write("										<ul>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000500050001\");'>안마의자</a></li>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000500050002\");'>안마기/마사지기</a></li>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000500050003\");'>찜질기/찜질팩/매트</a></li>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000500050004\");'>건강측정용품</a></li>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000500050005\");'>발관리용품</a></li>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000500050006\");'>실버보행보조용품</a></li>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000500050007\");'>건강용품</a></li>");
document.write("										</ul>");
document.write("									</div>");
document.write("								</div></div>");
document.write("							</li>");
document.write("							<li class='d1'>");
document.write("								<a href='javascript:goCategorySpecList(\"C0210006\");'><img src='//simage.lottemart.com/images/contentimg/special/digi-lnb-06-off.gif' alt='TV/냉장고/세탁기'></a>");
document.write("								<div id='display_6' class='digi_display' style='display:none;'><div class='con'>");
document.write("									<div class='col1'>");
document.write("										<h4>");
document.write("											<a href='javascript:goCategorySpecList(\"C02100060001\");'>TV/DVD</a>");
document.write("										</h4>");
document.write("										<ul>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000600010001\");'>PDPTV</a></li>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000600010002\");'>LCDTV</a></li>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000600010003\");'>LEDTV</a></li>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000600010004\");'>TV악세서리</a></li>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000600010005\");'>TV리모컨</a></li>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000600010006\");'>DVD/블루레이플레이어</a></li>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000600010007\");'>홈씨어터</a></li>");
document.write("										</ul>");
document.write("									</div>");
document.write("									<div class='col2'>");
document.write("										<h4>");
document.write("											<a href='javascript:goCategorySpecList(\"C02100060002\");'>냉장고/김치냉장고</a>");
document.write("										</h4>");
document.write("										<ul>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000600020001\");'>양문형냉장고</a></li>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000600020002\");'>냉장고</a></li>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000600020003\");'>기능성냉장고</a></li>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000600020004\");'>뚜껑식김치냉장고</a></li>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000600020005\");'>스탠드형김치냉장고</a></li>");
document.write("										</ul>");
document.write("									</div>");
document.write("									<div class='col3'>");
document.write("										<h4>");
document.write("											<a href='javascript:goCategorySpecList(\"C02100060003\");'>세탁기</a>");
document.write("										</h4>");
document.write("										<ul>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000600030001\");'>세탁기</a></li>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000600030002\");'>드럼세탁기</a></li>");
document.write("											<li><a href='javascript:goCategorySpecList(\"C021000600030003\");'>기능성세탁기/의류건조기</a></li>");
document.write("										</ul>");
document.write("									</div>");
document.write("								</div></div>");
document.write("							</li>");
document.write("						</ul>");
document.write("					</div>");

					$(document).ready(function(){
						spread_gnb( jQuery('#digi_lnb') );
					});
