document.write(" 		<div class='lnb'>");
document.write(" 			<div id='pet_lnb'>");
document.write(" 				<ul>");
document.write(" 					<li class='d1'>");
document.write(" 						<a class='d1' href='javascript:goCategorySpecList(&quot;C0230001&quot;);'><img alt='애견식품' src='//simage.lottemart.com/images/contentimg/special/pet-lnb-01-off.gif'></a>");
document.write(" 						<div style='display:none;' class='toy_display' id='display_1'><div class='con'>");
document.write(" 							<div class='col1'>");
document.write(" 								<dl class='disp_1_1'>");
document.write(" 									<dt><a href='javascript:goCategorySpecList(&quot;C02300010001&quot;);'>브랜드사료</a></dt>");
document.write(" 									<dd>");
document.write(" 											<a href='javascript:goCategorySpecList(&quot;C023000100010001&quot;);'><span>도비(DOBY)</span></a>");
document.write(" 									</dd>");
document.write(" 									<dd>");
document.write(" 										<a href='javascript:goCategorySpecList(&quot;C023000100010002&quot;);'><span>뉴트라골드홀리스틱</span></a>");
document.write(" 									</dd>");
document.write(" 										<dd>");
document.write(" 											<a href='javascript:goCategorySpecList(&quot;C023000100010003&quot;);'><span>프리미엄엣지</span></a>");
document.write(" 									</dd>");
document.write(" 										<dd>");
document.write(" 											<a href='javascript:goCategorySpecList(&quot;C023000100010004&quot;);'><span>사이언스</span></a>");
document.write(" 									</dd>");
document.write(" 										<dd>");
document.write(" 											<a href='javascript:goCategorySpecList(&quot;C023000100010005&quot;);'><span>네츄럴코어</span></a>");
document.write(" 									</dd>");
document.write(" 									<dd>");
document.write(" 										<a href='javascript:goCategorySpecList(&quot;C023000100010006&quot;);'><span>퓨리나</span></a>");
document.write(" 									</dd>");
document.write(" 									<dd>");
document.write(" 										<a href='javascript:goCategorySpecList(&quot;C023000100010007&quot;);'><span>유카누바</span></a>");
document.write(" 									</dd>");
document.write(" 									<dd>");
document.write(" 										<a href='javascript:goCategorySpecList(&quot;C023000100010008&quot;);'><span>기타 수입 브랜드</span></a>");
document.write(" 									</dd>");
document.write(" 								</dl>");
document.write(" 							</div>");
document.write(" 							<div class='col2 '>");
document.write(" 								<dl class='disp_1_2'>");
document.write(" 									<dt><a href='javascript:goCategorySpecList(&quot;C02300010002&quot;);'>연령/기능별사료</a></dt>");
document.write(" 									<dd>");
document.write(" 										<a href='javascript:goCategorySpecList(&quot;C023000100020001;);'><span>분유/이유식</span></a>");
document.write(" 									</dd>");
document.write(" 									<dd>");
document.write(" 										<a href='javascript:goCategorySpecList(&quot;C023000100020002&quot;);'><span>자견용(1년생 미만)</span></a>");
document.write(" 									</dd>");
document.write(" 									<dd>");
document.write(" 										<a href='javascript:goCategorySpecList(&quot;C023000100020003&quot;);'><span>성견용(1년생 이상)</span></a>");
document.write(" 									</dd>");
document.write(" 									<dd>");
document.write(" 										<a href='javascript:goCategorySpecList(&quot;C023000100020004&quot;);'><span>노령견(7년생 이상)</span></a>");
document.write(" 									</dd>");
document.write(" 									<dd>");
document.write(" 										<a href='javascript:goCategorySpecList(&quot;C023000100020005&quot;);'><span>전견용(모든 연령)</span></a>");
document.write(" 									</dd>");
document.write(" 									<dd>");
document.write(" 										<a href='javascript:goCategorySpecList(&quot;C023000100020006&quot;);'><span>기능성사료</span></a>");
document.write(" 									</dd>");
document.write(" 								</dl>");
document.write(" 							</div>");
document.write(" 							<div class='col3'>");
document.write(" 								<dl class='disp_1_3'>");
document.write(" 									<dt><a href='javascript:goCategorySpecList(&quot;C02300010003&quot;);'>간식/영양제</a></dt>");
document.write(" 									<dd>");
document.write(" 										<a href='javascript:goCategorySpecList(&quot;C023000100030001&quot;);'><span>습식캔/파우치</span></a>");
document.write(" 									</dd>");
document.write(" 									<dd>");
document.write(" 										<a href='javascript:goCategorySpecList(&quot;C023000100030002&quot;);'><span>육포/사사미</span></a>");
document.write(" 									</dd>");
document.write(" 									<dd>");
document.write(" 										<a href='javascript:goCategorySpecList(&quot;C023000100030003&quot;);'><span>져키류</span></a>");
document.write(" 									</dd>");
document.write(" 									<dd>");
document.write(" 										<a href='javascript:goCategorySpecList(&quot;C023000100030004&quot;);'><span>일반껌</span></a>");
document.write(" 									</dd>");
document.write(" 									<dd>");
document.write(" 										<a href='javascript:goCategorySpecList(&quot;C023000100030005&quot;);'><span>기능성껌</span></a>");
document.write(" 									</dd>");
document.write(" 									<dd>");
document.write(" 										<a href='javascript:goCategorySpecList(&quot;C023000100030006&quot;);'><span>비스켓/쿠키</span></a>");
document.write(" 									</dd>");
document.write(" 										<dd>");
document.write(" 										<a href='javascript:goCategorySpecList(&quot;C023000100030007&quot;);'><span>영양제</span></a>");
document.write(" 									</dd>");
document.write(" 								</dl>");
document.write(" 							</div>");
document.write(" 						</div></div>");
document.write(" 					</li>");
document.write(" 					<li class='d1'>");
document.write(" 						<a class='d1' href='javascript:goCategorySpecList(&quot;C0230002&quot;);'><img alt='애견용품' src='//simage.lottemart.com/images/contentimg/special/pet-lnb-02-off.gif'></a>");
document.write(" 						<div style='display: none;' class='toy_display' id='display_2'><div class='con'>");
document.write(" 							<div class='col1' >");
document.write(" 								<dl class='disp_2_1'>");
document.write(" 									<dt><a href='javascript:goCategorySpecList(&quot;C02300020001&quot;);'>목욕용품</a></dt>");
document.write(" 									<dd>");
document.write(" 										<a href='javascript:goCategorySpecList(&quot;C023000200010001&quot;);'><span>샴푸/린스</span></a>");
document.write(" 									</dd>");
document.write(" 									<dd>");
document.write(" 										<a href='javascript:goCategorySpecList(&quot;C023000200010002&quot;);'><span>귀/눈/구강관련</span></a>");
document.write(" 									</dd>");
document.write(" 									<dd>");
document.write(" 										<a href='javascript:goCategorySpecList(&quot;C023000200010003&quot;);'><span>타올/티슈</span></a>");
document.write(" 									</dd>");
document.write(" 									<dd>");
document.write(" 										<a href='javascript:goCategorySpecList(&quot;C023000200010004&quot;);'><span>기타</span></a>");
document.write(" 									</dd>");
document.write(" 								</dl>");
document.write(" 								<dl class='disp_2_2'>");
document.write(" 									<dt><a href='javascript:goCategorySpecList(&quot;C02300020005&quot;);'>의류/액세서리</a></dt>");
document.write(" 									<dd>");
document.write(" 										<a href='javascript:goCategorySpecList(&quot;C023000200050001&quot;);'><span>티셔츠</span></a>");
document.write(" 									</dd>");
document.write(" 									<dd>");
document.write(" 										<a href='javascript:goCategorySpecList(&quot;C023000200050002&quot;);'><span>원피스</span></a>");
document.write(" 									</dd>");
document.write(" 									<dd>");
document.write(" 										<a href='javascript:goCategorySpecList(&quot;C023000200050003&quot;);'><span>올인원/자켓</span></a>");
document.write(" 									</dd>");
document.write(" 									<dd>");
document.write(" 										<a href='javascript:goCategorySpecList(&quot;C023000200050004&quot;);'><span>신발/양말</span></a>");
document.write(" 									</dd>");
document.write(" 									<dd>");
document.write(" 										<a href='javascript:goCategorySpecList(&quot;C023000200050005&quot;);'><span>목걸이/이름표</span></a>");
document.write(" 									</dd>");
document.write(" 									<dd>");
document.write(" 										<a href='javascript:goCategorySpecList(&quot;C023000200050006&quot;);'><span>헤어액세서리</span></a>");
document.write(" 									</dd>");
document.write(" 									<dd>");
document.write(" 										<a href='javascript:goCategorySpecList(&quot;C023000200050007&quot;);'><span>패션소품/팬시</span></a>");
document.write(" 									</dd>");
document.write(" 								</dl>");
document.write(" 							</div>");
document.write(" 							<div class='col2 '>");
document.write(" 								<dl class='disp_2_3'>");
document.write(" 									<dt><a href='javascript:goCategorySpecList(&quot;C02300020002&quot;);'>미용용품</a></dt>");
document.write(" 									<dd>");
document.write(" 										<a href='javascript:goCategorySpecList(&quot;C023000200020001&quot;);'><span>브러쉬류</span></a>");
document.write(" 									</dd>");
document.write(" 									<dd>");
document.write(" 										<a href='javascript:goCategorySpecList(&quot;C023000200020002&quot;);'><span>클리퍼/미용가위</span></a>");
document.write(" 									</span></dd>");
document.write(" 									<dd>");
document.write(" 										<a href='javascript:goCategorySpecList(&quot;C023000200020003&quot;);'><span>발톱깍이</span></a>");
document.write(" 									</dd>");
document.write(" 									<dd>");
document.write(" 										<a href='javascript:goCategorySpecList(&quot;C023000200020004&quot;);'><span>기타</span></a>");
document.write(" 									</dd>");
document.write(" 								</dl>");
document.write(" 								<dl class='disp_2_4 '>");
document.write(" 									<dt><a href='javascript:goCategorySpecList(&quot;C02300020006&quot;);'>장난감/식기</a></dt>");
document.write(" 									<dd>");
document.write(" 										<a href='javascript:goCategorySpecList(&quot;C023000200060001&quot;);'><span>장난감/훈련용품</span></a>");
document.write(" 									</dd>");
document.write(" 									<dd>");
document.write(" 										<a href='javascript:goCategorySpecList(&quot;C023000200060002&quot;);'><span>일반식기</span></a>");
document.write(" 									</dd>");
document.write(" 									<dd>");
document.write(" 										<a href='javascript:goCategorySpecList(&quot;C023000200060003&quot;);'><span>자동/반자동 급식기</span></a>");
document.write(" 									</dd>");
document.write(" 									<dd>");
document.write(" 										<a href='javascript:goCategorySpecList(&quot;C023000200060004&quot;);'><span>급수기/젖병</span></a>");
document.write(" 									</dd>");
document.write(" 									<dd>");
document.write(" 										<a href='javascript:goCategorySpecList(&quot;C023000200060005&quot;);'><span>기타</span></a>");
document.write(" 									</dd>");
document.write(" 								</dl>");
document.write(" 							</div>");
document.write(" 							<div class='col3 '>");
document.write(" 								<dl class='disp_2_5'>");
document.write(" 									<dt><a href='javascript:goCategorySpecList(&quot;C02300020003&quot;);'>배변용품</a></dt>");
document.write(" 									<dd>");
document.write(" 										<a href='javascript:goCategorySpecList(&quot;C023000200030001&quot;);'><span>배변패드</span></a>");
document.write(" 									</dd>");
document.write(" 									<dd>");
document.write(" 										<a href='javascript:goCategorySpecList(&quot;C023000200030002&quot;);'><span>배변판</span></a>");
document.write(" 									</dd>");
document.write(" 									<dd>");
document.write(" 										<a href='javascript:goCategorySpecList(&quot;C023000200030003&quot;);'><span>기저귀/팬티</span></a>");
document.write(" 									</dd>");
document.write(" 									<dd>");
document.write(" 										<a href='javascript:goCategorySpecList(&quot;C023000200030004&quot;);'><span>탈취/소독</span></a>");
document.write(" 									</dd>");
document.write(" 									<dd>");
document.write(" 										<a href='javascript:goCategorySpecList(&quot;C023000200030005&quot;);'><span>기타</span></a>");
document.write(" 									</dd>");
document.write(" 								</dl>");
document.write(" 								<dl class='disp_2_6'>");
document.write(" 									<dt><a href='javascript:goCategorySpecList(&quot;C02300020007&quot;);'>하우스/이동장</a></dt>");
document.write(" 									<dd>");
document.write(" 										<a href='javascript:goCategorySpecList(&quot;C023000200070001&quot;);'><span>방석/스텝</span></a>");
document.write(" 									</dd>");
document.write(" 									<dd>");
document.write(" 										<a href='javascript:goCategorySpecList(&quot;C023000200070002&quot;);'><span>하우스</span></a>");
document.write(" 									</dd>");
document.write(" 									<dd>");
document.write(" 										<a href='javascript:goCategorySpecList(&quot;C023000200070003&quot;);'><span>이동장(캐리어)</span></a>");
document.write(" 									</dd>");
document.write(" 									<dd>");
document.write(" 										<a href='javascript:goCategorySpecList(&quot;C023000200070004&quot;);'><span>펜스</span></a>");
document.write(" 									</dd>");
document.write(" 								</dl>");
document.write(" 							</div>");
document.write(" 							<div class='col4 '>");
document.write(" 									<dl class='disp_2_7'>");
document.write(" 										<dt><a href='javascript:goCategorySpecList(&quot;C02300020004&quot;);'>애견줄</a></dt>");
document.write(" 										<dd>");
document.write(" 											<a href='javascript:goCategorySpecList(&quot;C023000200040001&quot;);'><span>목줄</span></a>");
document.write(" 										</dd>");
document.write(" 										<dd>");
document.write(" 											<a href='javascript:goCategorySpecList(&quot;C023000200040002&quot;);'><span>가슴줄(하네스)</span></a>");
document.write(" 										</dd>");
document.write(" 										<dd>");
document.write(" 											<a href='javascript:goCategorySpecList(&quot;C023000200040003&quot;);'><span>일반리드줄</span></a>");
document.write(" 										</dd>");
document.write(" 										<dd>");
document.write(" 											<a href='javascript:goCategorySpecList(&quot;C023000200040004&quot;);'><span>자동리드줄</span></a>");
document.write(" 										</dd>");
document.write(" 										<dd>");
document.write(" 											<a href='javascript:goCategorySpecList(&quot;C023000200040005&quot;);'><span>가죽줄/체인</span></a>");
document.write(" 										</dd>");
document.write(" 										<dd>");
document.write(" 											<a href='javascript:goCategorySpecList(&quot;C023000200040006&quot;);'><span>나일론줄</span></a>");
document.write(" 										</dd>");
document.write(" 									</dl>");
document.write(" 								</div>");
document.write(" 						</div></div>");
document.write(" 					</li>");
document.write(" 					<li class='d1'>");
document.write(" 						<a class='d1' href='javascript:goCategorySpecList(&quot;C0230003&quot;);'><img alt='고양이식품' src='//simage.lottemart.com/images/contentimg/special/pet-lnb-03-off.gif'></a>");
document.write(" 						<div style='display: none;' class='toy_display' id='display_3'><div class='con'>");
document.write(" 							<div class='col1 '>");
document.write(" 								<dl class='disp_3_1'>");
document.write(" 									<dt><a href='javascript:goCategorySpecList(&quot;C02300030001&quot;);'>브랜드사료</a></dt>");
document.write(" 										<dd>");
document.write(" 											<a href='javascript:goCategorySpecList(&quot;C023000300010001&quot;);'><span>치킨수프</span></a>");
document.write(" 										</dd>");
document.write(" 										<dd>");
document.write(" 											<a href='javascript:goCategorySpecList(&quot;C023000300010002&quot;);'><span>프리미엄엣지</span></a>");
document.write(" 										</dd>");
document.write(" 										<dd>");
document.write(" 											<a href='javascript:goCategorySpecList(&quot;C023000300010003&quot;);'><span>뉴트라골드홀리스틱</span></a>");
document.write(" 										</dd>");
document.write(" 										<dd>");
document.write(" 											<a href='javascript:goCategorySpecList(&quot;C023000300010004&quot;);'><span>사이언스</span></a>");
document.write(" 										</dd>");
document.write(" 										<dd>");
document.write(" 											<a href='javascript:goCategorySpecList(&quot;C023000300010005&quot;);'><span>아이암스</span></a>");
document.write(" 										</dd>");
document.write(" 										<dd>");
document.write(" 											<a href='javascript:goCategorySpecList(&quot;C023000300010006&quot;);'><span>프리스키</span></a>");
document.write(" 										</dd>");
document.write(" 										<dd>");
document.write(" 											<a href='javascript:goCategorySpecList(&quot;C023000300010007&quot;);'><span>위스카스</span></a>");
document.write(" 										</dd>");
document.write(" 										<dd>");
document.write(" 											<a href='javascript:goCategorySpecList(&quot;C023000300010008&quot;);'><span>기타 수입 브랜드</span></a>");
document.write(" 										</dd>");
document.write(" 								</dl>");
document.write(" 							</div>");
document.write(" 							<div class='col2'>");
document.write(" 								<dl class='disp_3_2'>");
document.write(" 									<dt><a href='javascript:goCategorySpecList(&quot;C02300030002&quot;);'>연령/기능별사료</a></dt>");
document.write(" 										<dd>");
document.write(" 											<a href='javascript:goCategorySpecList(&quot;C023000300020001&quot;);'><span>분유/이유식/우유</span></a>");
document.write(" 										</dd>");
document.write(" 										<dd>");
document.write(" 											<a href='javascript:goCategorySpecList(&quot;C023000300020002&quot;);'><span>자묘용(1년생 미만)</span></a>");
document.write(" 										</dd>");
document.write(" 										<dd>");
document.write(" 											<a href='javascript:goCategorySpecList(&quot;C023000300020003&quot;);'><span>성묘용(1년생 이상)</span></a>");
document.write(" 										</dd>");
document.write(" 										<dd>");
document.write(" 											<a href='javascript:goCategorySpecList(&quot;C023000300020004&quot;);'><span>전연령용(모든 고양이)</span></a>");
document.write(" 										</dd>");
document.write(" 										<dd>");
document.write(" 											<a href='javascript:goCategorySpecList(&quot;C023000300020005&quot;);'><span>노령묘용(7년생 이상)</span></a>");
document.write(" 										</dd>");
document.write(" 										<dd>");
document.write(" 											<a href='javascript:goCategorySpecList(&quot;C023000300020006&quot;);'><span>기능성사료</span></a>");
document.write(" 										</dd>");
document.write(" 								</dl>");
document.write(" 							</div>");
document.write(" 							<div class='col3'>");
document.write(" 								<dl class='disp_3_3 '>");
document.write(" 									<dt><a href='javascript:goCategorySpecList(&quot;C02300030003&quot;);'>캔/파우치</a></dt>");
document.write(" 										<dd>");
document.write(" 											<a href='javascript:goCategorySpecList(&quot;C023000300030001&quot;);'><span>캔/통조림</span></a>");
document.write(" 										</dd>");
document.write(" 										<dd>");
document.write(" 											<a href='javascript:goCategorySpecList(&quot;C023000300030002&quot;);'><span>파우치</span></a>");
document.write(" 										</dd>");
document.write(" 										<dd>");
document.write(" 											<a href='javascript:goCategorySpecList(&quot;C023000300030003&quot;);'><span>알뜰 캔세트</span></a>");
document.write(" 										</dd>");
document.write(" 								</dl>");
document.write(" 							</div>");
document.write(" 							<div class='col3'>");
document.write(" 								<dl class='disp_3_4'>");
document.write(" 									<dt><a href='javascript:goCategorySpecList(&quot;C02300030004&quot;);'>간식/영양제</a></dt>");
document.write(" 									<dd>");
document.write(" 										<a href='javascript:goCategorySpecList(&quot;C023000300040001&quot;);'>건어물/슬라이스</a>");
document.write(" 									</dd>");
document.write(" 									<dd>");
document.write(" 										<a href='javascript:goCategorySpecList(&quot;C023000300040002&quot;);'>훈제/소시지</a>");
document.write(" 									</dd>");
document.write(" 									<dd>");
document.write(" 										<a href='javascript:goCategorySpecList(&quot;C023000300040003&quot;);'>드롭스/트릿</a>");
document.write(" 									</dd>");
document.write(" 									<dd>");
document.write(" 										<a href='javascript:goCategorySpecList(&quot;C023000300040004&quot;);'>져키/스틱</a>");
document.write(" 									</dd>");
document.write(" 									<dd>");
document.write(" 										<a href='javascript:goCategorySpecList(&quot;C023000300040005&quot;);'>영양제</a>");
document.write(" 									</dd>");
document.write(" 								</dl>");
document.write(" 							</div>");
document.write(" 						</div></div>");
document.write(" 					</li>");
document.write(" 					<li class='d1'>");
document.write(" 						<a class='d1' href='javascript:goCategorySpecList(&quot;C0230004&quot;);'><img alt='고양이용품' src='//simage.lottemart.com/images/contentimg/special/pet-lnb-04-off.gif'></a>");
document.write(" 						<div style='display:none;' class='toy_display' id='display_4'><div class='con'>");
document.write(" 							<div class='col1' >");
document.write(" 								<dl class='disp_4_1'>");
document.write(" 									<dt><a href='javascript:goCategorySpecList(&quot;C02300040001&quot;);'>모래</a></dt>");
document.write(" 									<dd>");
document.write(" 										<a href='javascript:goCategorySpecList(&quot;C023000400010001&quot;);'><span>응고형</span></a>");
document.write(" 									</dd>");
document.write(" 									<dd>");
document.write(" 										<a href='javascript:goCategorySpecList(&quot;C023000400010002&quot;);'><span>흡수형</span></a>");
document.write(" 									</dd>");
//document.write(" 									<dd>");
//document.write(" 										<a href='javascript:goCategorySpecList(&quot;C023000400010003&quot;);'><span>알뜰 모래세트</span></a>");
//document.write(" 									</dd>");
document.write(" 									<dd>");
document.write(" 										<a href='javascript:goCategorySpecList(&quot;C023000400010004&quot;);'><span>탈취/소독</span></a>");
document.write(" 									</dd>");
document.write(" 								</dl>");
document.write(" 								<dl class='disp_4_2 '>");
document.write(" 									<dt><a href='javascript:goCategorySpecList(&quot;C02300040004&quot;);'>스크래쳐/캣타워</a></dt>");
document.write(" 									<dd>");
document.write(" 										<a href='javascript:goCategorySpecList(&quot;C023000400040001&quot;);'><span>스크래쳐</span></a>");
document.write(" 									</dd>");
document.write(" 									<dd>");
document.write(" 										<a href='javascript:goCategorySpecList(&quot;C023000400040002&quot;);'><span>터널/박스</span></a>");
document.write(" 									</dd>");
document.write(" 									<dd>");
document.write(" 										<a href='javascript:goCategorySpecList(&quot;C023000400040003&quot;);'><span>캣타워</span></a>");
document.write(" 									</dd>");
document.write(" 								</dl>");
document.write(" 							</div>");
document.write(" 							<div class='col2 '>");
document.write(" 								<dl class='disp_4_3'>");
document.write(" 									<dt><a href='javascript:goCategorySpecList(&quot;C02300040002&quot;);'>화장실</a></dt>");
document.write(" 									<dd>");
document.write(" 										<a href='javascript:goCategorySpecList(&quot;C023000400020001&quot;);'><span>하우스형 화장실</span></a>");
document.write(" 									</dd>");
document.write(" 									<dd>");
document.write(" 										<a href='javascript:goCategorySpecList(&quot;C023000400020002&quot;);'><span>평판형 화장실</span></a>");
document.write(" 									</span></dd>");
document.write(" 									<dd>");
document.write(" 										<a href='javascript:goCategorySpecList(&quot;C023000400020003&quot;);'><span>배변용품</span></a>");
document.write(" 									</dd>");
document.write(" 								</dl>");
document.write(" 								<dl class='disp_4_4 '>");
document.write(" 									<dt><a href='javascript:goCategorySpecList(&quot;C02300040005&quot;);'>목욕/미용</a></dt>");
document.write(" 									<dd>");
document.write(" 										<a href='javascript:goCategorySpecList(&quot;C023000400050001&quot;);'><span>삼푸/린스</span></a>");
document.write(" 									</dd>");
document.write(" 									<dd>");
document.write(" 										<a href='javascript:goCategorySpecList(&quot;C023000400050002&quot;);'><span>눈/귀/구강관련</span></a>");
document.write(" 									</dd>");
document.write(" 									<dd>");
document.write(" 										<a href='javascript:goCategorySpecList(&quot;C023000400050003&quot;);'><span>브러쉬/빗</span></a>");
document.write(" 									</dd>");
document.write(" 									<dd>");
document.write(" 										<a href='javascript:goCategorySpecList(&quot;C023000400050004&quot;);'><span>발톱깍이/가위</span></a>");
document.write(" 									</dd>");
document.write(" 								</dl>");
document.write(" 							</div>");
document.write(" 							<div class='col3 '>");
document.write(" 								<dl class='disp_4_5'>");
document.write(" 									<dt><a href='javascript:goCategorySpecList(&quot;C02300040003&quot;);'>장난감/캣닙</a></dt>");
document.write(" 									<dd>");
document.write(" 										<a href='javascript:goCategorySpecList(&quot;C023000400030001&quot;);'><span>낚시대/막대</span></a>");
document.write(" 									</dd>");
document.write(" 									<dd>");
document.write(" 										<a href='javascript:goCategorySpecList(&quot;C023000400030002&quot;);'><span>인형/쿠션</span></a>");
document.write(" 									</dd>");
document.write(" 									<dd>");
document.write(" 										<a href='javascript:goCategorySpecList(&quot;C023000400030003&quot;);'><span>공/기타</span></a>");
document.write(" 									</dd>");
document.write(" 									<dd>");
document.write(" 										<a href='javascript:goCategorySpecList(&quot;C023000400030004&quot;);'><span>캣닙</span></a>");
document.write(" 									</dd>");
document.write(" 								</dl>");
document.write(" 								<dl class='disp_4_6'>");
document.write(" 									<dt><a href='javascript:goCategorySpecList(&quot;C02300040006&quot;);'>하우스/캐리어</a></dt>");
document.write(" 									<dd>");
document.write(" 										<a href='javascript:goCategorySpecList(&quot;C023000400060001&quot;);'><span>하우스/방석</span></a>");
document.write(" 									</dd>");
document.write(" 									<dd>");
document.write(" 										<a href='javascript:goCategorySpecList(&quot;C023000400060002&quot;);'><span>이동장/가방</span></a>");
document.write(" 									</dd>");
document.write(" 									<dd>");
document.write(" 										<a href='javascript:goCategorySpecList(&quot;C023000400060003&quot;);'><span>철장</span></a>");
document.write(" 									</dd>");
document.write(" 								</dl>");
document.write(" 							</div>");
document.write(" 						</div></div>");
document.write(" 					</li>");
document.write(" 					<li class='d1'>");
document.write(" 						<a class='d1' href='javascript:goCategorySpecList(&quot;C0230005&quot;);'><img alt='수족관 기타동물' src='//simage.lottemart.com/images/contentimg/special/pet-lnb-05-off.gif'></a>");
document.write(" 						<div style='display: none;' class='toy_display' id='display_5'><div class='con'>");
document.write(" 							<div class='col1' >");
document.write(" 								<dl class='disp_5_1'>");
document.write(" 									<dt><a href='javascript:goCategorySpecList(&quot;C02300050001&quot;);'>관상어</a></dt>");
document.write(" 									<dd>");
document.write(" 										<a href='javascript:goCategorySpecList(&quot;C023000500010001&quot;);'><span>사료</span></a>");
document.write(" 									</dd>");
document.write(" 									<dd>");
document.write(" 										<a href='javascript:goCategorySpecList(&quot;C023000500010002&quot;);'><span>약품</span></a>");
document.write(" 									</dd>");
document.write(" 									<dd>");
document.write(" 										<a href='javascript:goCategorySpecList(&quot;C023000500010003&quot;);'><span>어항</span></a>");
document.write(" 									</dd>");
document.write(" 									<dd>");
document.write(" 										<a href='javascript:goCategorySpecList(&quot;C023000500010004&quot;);'><span>액세서리</span></a>");
document.write(" 									</dd>");
document.write(" 									<dd>");
document.write(" 										<a href='javascript:goCategorySpecList(&quot;C023000500010005&quot;);'><span>용품 및 기타</span></a>");
document.write(" 									</dd>");
document.write(" 								</dl>");
document.write(" 								<dl class='disp_5_2 '>");
document.write(" 									<dt><a href='javascript:goCategorySpecList(&quot;C02300050004&quot;);'>애완소동물</a></dt>");
document.write(" 									<dd>");
document.write(" 										<a href='javascript:goCategorySpecList(&quot;C023000500040001&quot;);'><span>사료</span></a>");
document.write(" 									</dd>");
document.write(" 									<dd>");
document.write(" 										<a href='javascript:goCategorySpecList(&quot;C023000500040002&quot;);'><span>용품 및 기타</span></a>");
document.write(" 									</dd>");
document.write(" 								</dl>");
document.write(" 							</div>");
document.write(" 							<div class='col2 '>");
document.write(" 								<dl class='disp_5_3'>");
document.write(" 									<dt><a href='javascript:goCategorySpecList(&quot;C02300050002&quot;);'>관상조</a></dt>");
document.write(" 									<dd>");
document.write(" 										<a href='javascript:goCategorySpecList(&quot;C023000500020001&quot;);'><span>사료</span></a>");
document.write(" 									</dd>");
document.write(" 									<dd>");
document.write(" 										<a href='javascript:goCategorySpecList(&quot;C023000500020002&quot;);'><span>용품 및 기타</span></a>");
document.write(" 									</span></dd>");
document.write(" 								</dl>");
document.write(" 								<dl class='disp_5_4 r2'>");
document.write(" 									<dt><a href='javascript:goCategorySpecList(&quot;C02300050005&quot;);'>기타용품</a></dt>");
document.write(" 									<dd>");
document.write(" 										<a href='javascript:goCategorySpecList(&quot;C023000500050001&quot;);'><span>특이 동물 용품</span></a>");
document.write(" 									</dd>");
document.write(" 								</dl>");
document.write(" 							</div>");
document.write(" 							<div class='col3 '>");
document.write(" 								<dl class='disp_5_5'>");
document.write(" 									<dt><a href='javascript:goCategorySpecList(&quot;C02300050003&quot;);'>애완곤충용품</a></dt>");
document.write(" 									<dd>");
document.write(" 										<a href='javascript:goCategorySpecList(&quot;C023000500030001&quot;);'><span>사료</span></a>");
document.write(" 									</dd>");
document.write(" 									<dd>");
document.write(" 										<a href='javascript:goCategorySpecList(&quot;C023000500030002&quot;);'><span>용품 및 기타</span></a>");
document.write(" 									</dd>");
document.write(" 								</dl>");
document.write(" 							</div>");
document.write(" 						</div></div>");
document.write(" 					</li>");
document.write(" 				</ul>");
document.write(" 			</div>");
document.write(" 		</div>");


				$(document).ready(function(){
					spread_gnb( jQuery('#toy_lnb') );
				});
