var _ux_category = '<ul id="menu2">'
+'	<li class="menu2_1"><a href="#1"><span>신선/가공</span></a>'
+'		<ul class="depth2" style="display:none;">'
+'			<li><a href="#2">쌀</a>'
+'				<ul class="depth3">'
+'					<li><a href="#2">쌀 중량별</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">20Kg</a></li>'
+'							<li><a href="#2">10Kg</a></li>'
+'							<li><a href="#2">10Kg이하/소포장</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">즉석 도정미</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">10Kg 이상</a></li>'
+'							<li><a href="#2">10Kg이하/소포장</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">친환경 양곡</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">10Kg 이상</a></li>'
+'							<li><a href="#2">10Kg이하/소포장</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">산지무료배송</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">20Kg</a></li>'
+'							<li><a href="#2">10Kg</a></li>'
+'							<li><a href="#2">10Kg이하/소포장</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">찹쌀/현미/흑미</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">찹쌀</a></li>'
+'							<li><a href="#2">현미</a></li>'
+'							<li><a href="#2">흑미</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">보리/콩/팥</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">보리</a></li>'
+'							<li><a href="#2">콩/팥</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">혼합곡/기타</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">혼합곡</a></li>'
+'							<li><a href="#2">녹두/율무</a></li>'
+'							<li><a href="#2">참깨/들깨</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">잡곡류</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">콩/서리태</a></li>'
+'							<li><a href="#2">보리/기타</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">세일상품</a>'
+'					</li>'
+'				</ul>'
+'			</li>'
+'			<li><a href="#2">채소</a>'
+'				<ul class="depth3">'
+'					<li><a href="#2">상추/깻잎/쌈채소</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">상추/껫잎</a></li>'
+'							<li><a href="#2">쌈채소</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">파프리카/고추/열매채소</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">파프리카/피망</a></li>'
+'							<li><a href="#2">고추/건고추</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">두부/콩나물</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">찌개용 두부</a></li>'
+'							<li><a href="#2">부침용 두부</a></li>'
+'							<li><a href="#2">혼합/기능성 두부</a></li>'
+'							<li><a href="#2">순두부/연두부</a></li>'
+'							<li><a href="#2">묵</a></li>'
+'							<li><a href="#2">콩나물/숙주나물</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">당근/뿌리채소</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">당근</a></li>'
+'							<li><a href="#2">마/야콘</a></li>'
+'							<li><a href="#2">우엉/연근</a></li>'
+'							<li><a href="#2">더덕/기타</a></li>'
+'							<li><a href="#2">약초</a></li>'
+'							<li><a href="#2">콩나물/숙주나물</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">고구마/감자</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">고구마</a></li>'
+'							<li><a href="#2">감자</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">오이/호박/가지/옥수수</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">오이/가지</a></li>'
+'							<li><a href="#2">호박/애호박</a></li>'
+'							<li><a href="#2">옥수수</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">양배추/배추/무/김장채소</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">양배추/배추/무</a></li>'
+'							<li><a href="#2">부추/열무/알타리/갓</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">양파/마늘/생강/파</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">양파</a></li>'
+'							<li><a href="#2">마늘/생강</a></li>'
+'							<li><a href="#2">대파/쪽파</a></li>'
+'							<li><a href="#2">간편양념/채소</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">나물/시금치/잎줄기채소</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">시금치/미나리/쑥갓</a></li>'
+'							<li><a href="#2">잎줄기채소</a></li>'
+'							<li><a href="#2">건나물/기타 나물</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">브로콜리/양상추/샐러드</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">브로콜리/양상추</a></li>'
+'							<li><a href="#2">샐러드</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">새송이/느타리/버섯류</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">새송이/느타리</a></li>'
+'							<li><a href="#2">양송이/표고/팽이</a></li>'
+'							<li><a href="#2">건버섯</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">해초류</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">해초류</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">세일상품</a>'
+'					</li>'
+'				</ul>'
+'			</li>'
+'			<li><a href="#2">과일</a>'
+'				<ul class="depth3">'
+'					<li><a href="#2">수박/메론/참외</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">수박</a></li>'
+'							<li><a href="#2">메론</a></li>'
+'							<li><a href="#2">참외</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">토마토/자두/복숭아/포도</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">토마토</a></li>'
+'							<li><a href="#2">자두</a></li>'
+'							<li><a href="#2">복숭아</a></li>'
+'							<li><a href="#2">포도</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">바나나/오렌지/외국과일</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">바나나</a></li>'
+'							<li><a href="#2">오렌지</a></li>'
+'							<li><a href="#2">파인애플</a></li>'
+'							<li><a href="#2">자몽/레몬/석류</a></li>'
+'							<li><a href="#2">망고/체리/기타</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">감/곶감</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">감</a></li>'
+'							<li><a href="#2">곶감</a></li>'
+'							<li><a href="#2">감말랭이/홍시</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">키위/참다래</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">골드키위</a></li>'
+'							<li><a href="#2">그린키위</a></li>'
+'							<li><a href="#2">레드키위</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">감귤/한라봉</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">감귤/한라봉</a></li>'
+'							<li><a href="#2">천혜향/레드향/기타</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">사과/배</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">사과</a></li>'
+'							<li><a href="#2">배</a></li>'
+'							<li><a href="#2">사과/배 혼합</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">딸기/블루베리/매실/기타</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">딸기</a></li>'
+'							<li><a href="#2">블루베리</a></li>'
+'							<li><a href="#2">매실</a></li>'
+'							<li><a href="#2">기타과일</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">땅콩/대추/건과/견과류</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">건포도/건대추/건과일</a></li>'
+'							<li><a href="#2">밤/땅콩/호두/기타</a></li>'
+'							<li><a href="#2">아몬드/캐슈넛/피스타치오/기타</a></li>'
+'							<li><a href="#2">혼합견과</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">냉동/간편과일</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">냉동과일</a></li>'
+'							<li><a href="#2">간편과일</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">과일세트</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">과일바구니</a></li>'
+'							<li><a href="#2">사과</a></li>'
+'							<li><a href="#2">배</a></li>'
+'							<li><a href="#2">사과/배 혼합</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">세일상품</a>'
+'					</li>'
+'				</ul>'
+'			</li>'
+'			<li><a href="#2">정육/계란</a>'
+'				<ul class="depth3">'
+'					<li><a href="#2">한우</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">등심/안심/구이</a></li>'
+'							<li><a href="#2">갈비/찜</a></li>'
+'							<li><a href="#2">한우국거리/기타</a></li>'
+'							<li><a href="#2">사골/꼬리/우족</a></li>'
+'							<li><a href="#2">불고기/산적/장조림</a></li>'
+'							<li><a href="#2">간편포장 MAP</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">브랜드 한우</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">진심 한우</a></li>'
+'							<li><a href="#2">횡성 한우</a></li>'
+'							<li><a href="#2">영주 축협 한우</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">수입육</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">호주산</a></li>'
+'							<li><a href="#2">미국산</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">돼지고기</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">삼겹살/목심/구이</a></li>'
+'							<li><a href="#2">불고기/찌개/다짐육</a></li>'
+'							<li><a href="#2">갈비/찜/바비큐</a></li>'
+'							<li><a href="#2">장조림/돈까스/카레</a></li>'
+'							<li><a href="#2">소포장</a></li>'
+'							<li><a href="#2">간편포장 MAP</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">양념육/가공육</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">소고기</a></li>'
+'							<li><a href="#2">돼지고기</a></li>'
+'							<li><a href="#2">닭/오리고기</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">닭/오리고기</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">백숙용 닭고기</a></li>'
+'							<li><a href="#2">볶음탕용 닭고기</a></li>'
+'							<li><a href="#2">닭가슴살/안심</a></li>'
+'							<li><a href="#2">닭다리/날개/윙봉</a></li>'
+'							<li><a href="#2">오리</a></li>'
+'							<li><a href="#2">닭/오리훈제</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">계란</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">계란 10구이하</a></li>'
+'							<li><a href="#2">계란 15구이상</a></li>'
+'							<li><a href="#2">계란 30구</a></li>'
+'							<li><a href="#2">메추리알/기타</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">세일상품</a>'
+'					</li>'
+'				</ul>'
+'			</li>'
+'			<li><a href="#2">생선/건해산물</a>'
+'				<ul class="depth3">'
+'					<li><a href="#2">고등어/갈치/삼치/꽁치</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">고등어</a></li>'
+'							<li><a href="#2">갈치</a></li>'
+'							<li><a href="#2">삼치</a></li>'
+'							<li><a href="#2">꽁치</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">굴비/조기/옥돔/명태/기타</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">굴비/참조기</a></li>'
+'							<li><a href="#2">옥동</a></li>'
+'							<li><a href="#2">명태류</a></li>'
+'							<li><a href="#2">대구/가자미</a></li>'
+'							<li><a href="#2">열빙어/전어</a></li>'
+'							<li><a href="#2">참치/연어</a></li>'
+'							<li><a href="#2">임연수</a></li>'
+'							<li><a href="#2">기타생선</a></li>'
+'							<li><a href="#2">냉동간편포장</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">오징어/낙지</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">오징어</a></li>'
+'							<li><a href="#2">낙지/쭈꾸미</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">해산물/새우/게/장어</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">소라/골뱅이</a></li>'
+'							<li><a href="#2">장어/과메기</a></li>'
+'							<li><a href="#2">날치알/성게알/알류</a></li>'
+'							<li><a href="#2">굴/바지락살/새우살/기타</a></li>'
+'							<li><a href="#2">새우</a></li>'
+'							<li><a href="#2">꽃게/대게/붉은대게</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">전복/조개류</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">전복</a></li>'
+'							<li><a href="#2">조개류</a></li>'
+'							<li><a href="#2">꼬막/바지락/홍합</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">회</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">회</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">멸치/건새우</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">멸치</a></li>'
+'							<li><a href="#2">건새우</a></li>'
+'							<li><a href="#2">다시티백/분말류</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">조미김/생김</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">구운김/조미김</a></li>'
+'							<li><a href="#2">생김/파래김</a></li>'
+'							<li><a href="#2">도시락/김밥용김</a></li>'
+'							<li><a href="#2">김자반</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">미역/다시마</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">미역</a></li>'
+'							<li><a href="#2">다시마</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">건오징어/어포/육포</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">건오징어</a></li>'
+'							<li><a href="#2">진미채</a></li>'
+'							<li><a href="#2">어포/쥐초</a></li>'
+'							<li><a href="#2">육포</a></li>'
+'							<li><a href="#2">황태/북어</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">세일상품</a>'
+'					</li>'
+'				</ul>'
+'			</li>'
+'			<li><a href="#2">냉장/냉동</a>'
+'				<ul class="depth3">'
+'					<li><a href="#2">소시지/햄/베이컨</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">후랑크,비엔나</a></li>'
+'							<li><a href="#2">슬라이스햄/분절햄</a></li>'
+'							<li><a href="#2">라운드햄/소시지</a></li>'
+'							<li><a href="#2">베이컨</a></li>'
+'							<li><a href="#2">어린이 소시지</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">맛살/어묵/단무지</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">맛살</a></li>'
+'							<li><a href="#2">어묵</a></li>'
+'							<li><a href="#2">유부</a></li>'
+'							<li><a href="#2">곤약</a></li>'
+'							<li><a href="#2">단무지/쌈무</a></li>'
+'							<li><a href="#2">절임/피클</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">냉장면/냉장떡</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">우동/메밀/중화면</a></li>'
+'							<li><a href="#2">스파게티</a></li>'
+'							<li><a href="#2">칼국수/쫄면 외</a></li>'
+'							<li><a href="#2">떡/떡볶이</a></li>'
+'							<li><a href="#2">냉면</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">냉장반찬/포장김치</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">포장젓갈</a></li>'
+'							<li><a href="#2">무침/조림/절임/볶음 반찬류</a></li>'
+'							<li><a href="#2">게장/벌크젓갈</a></li>'
+'							<li><a href="#2">냉장장류</a></li>'
+'							<li><a href="#2">포기김치</a></li>'
+'							<li><a href="#2">맛김치/여행용김치</a></li>'
+'							<li><a href="#2">무/기타김치</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">아이스크림</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">바/콘 아이스크림</a></li>'
+'							<li><a href="#2">홈 아이스크림</a></li>'
+'							<li><a href="#2">구슬 아이스크림</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">만두/만두피</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">군만두</a></li>'
+'							<li><a href="#2">물만두</a></li>'
+'							<li><a href="#2">손/찜만두</a></li>'
+'							<li><a href="#2">교자만두</a></li>'
+'							<li><a href="#2">만두피</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">냉동간식/반찬</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">떡갈비/완자</a></li>'
+'							<li><a href="#2">동그랑땡</a></li>'
+'							<li><a href="#2">스테이크/패티</a></li>'
+'							<li><a href="#2">가스류 (돈/생선/치킨)</a></li>'
+'							<li><a href="#2">너겟/치킨/윙</a></li>'
+'							<li><a href="#2">감자/오징어/기타튀김</a></li>'
+'							<li><a href="#2">기타 (냉동떡/춘권피/꽃빵/낫또)</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">간편 조리식품</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">냉동 탕/국/찌개</a></li>'
+'							<li><a href="#2">냉동 밥/면류</a></li>'
+'							<li><a href="#2">냉장 간편식(밥/죽/반찬)</a></li>'
+'							<li><a href="#2">피자/핫도그/냉동케익 간식류</a></li>'
+'							<li><a href="#2">냉동반찬/야식/안주</a></li>'
+'							<li><a href="#2">떡</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">우유/요구르트</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">흰우유</a></li>'
+'							<li><a href="#2">기능성 흰우유</a></li>'
+'							<li><a href="#2">바나나/커피 가공우유</a></li>'
+'							<li><a href="#2">떠먹는 요구르트</a></li>'
+'							<li><a href="#2">마시는 요구르트</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">치즈/버터/디저트</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">슬라이스 치즈</a></li>'
+'							<li><a href="#2">자연/피자치즈</a></li>'
+'							<li><a href="#2">크림치즈</a></li>'
+'							<li><a href="#2">어린이용 치즈</a></li>'
+'							<li><a href="#2">버터/마가린</a></li>'
+'							<li><a href="#2">생크림/연유</a></li>'
+'							<li><a href="#2">냉장 디저트</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">세일상품</a>'
+'					</li>'
+'				</ul>'
+'			</li>'
+'			<li><a href="#2">가공식품/분유</a>'
+'				<ul class="depth3">'
+'					<li><a href="#2">라면/면류</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">낱개 봉지라면</a></li>'
+'							<li><a href="#2">박스 봉지라면</a></li>'
+'							<li><a href="#2">낱개 컵라면</a></li>'
+'							<li><a href="#2">박스 컵라면</a></li>'
+'							<li><a href="#2">국수</a></li>'
+'							<li><a href="#2">당면/건냉면</a></li>'
+'							<li><a href="#2">생면(우동/스파게티류)</a></li>'
+'							<li><a href="#2">스파게티/파스타류</a></li>'
+'							<li><a href="#2">수입면/쌈</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">즉석밥/죽/반찬</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">즉석밥/덮밥/국밥/누룽지</a></li>'
+'							<li><a href="#2">즉석/분말 죽</a></li>'
+'							<li><a href="#2">즉석/분말 스프</a></li>'
+'							<li><a href="#2">즉석 국/반찬</a></li>'
+'							<li><a href="#2">덮밥 소스/밥 양념</a></li>'
+'							<li><a href="#2">카레/짜장</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">통조림</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">참치 통조림</a></li>'
+'							<li><a href="#2">고등어/꽁치/골뱅이</a></li>'
+'							<li><a href="#2">옥수수/반찬 통조림</a></li>'
+'							<li><a href="#2">과일 통조림</a></li>'
+'							<li><a href="#2">스팸/햄 통조림</a></li>'
+'							<li><a href="#2">닭가슴살 통조림</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">가루/믹스류</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">밀가루</a></li>'
+'							<li><a href="#2">곡물가루/엿기름</a></li>'
+'							<li><a href="#2">부침/튀김가루</a></li>'
+'							<li><a href="#2">미숫가루/선식</a></li>'
+'							<li><a href="#2">홈메이드 믹스</a></li>'
+'							<li><a href="#2">제빵재료</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">장류/간장</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">고추장</a></li>'
+'							<li><a href="#2">된장/춘장</a></li>'
+'							<li><a href="#2">초고추장/쌈장</a></li>'
+'							<li><a href="#2">진/혼합간장</a></li>'
+'							<li><a href="#2">양조/한식간장</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">소스류/케찹/마요네즈	</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">케찹</a></li>'
+'							<li><a href="#2">마요네즈</a></li>'
+'							<li><a href="#2">드레싱</a></li>'
+'							<li><a href="#2">국물/양념소스</a></li>'
+'							<li><a href="#2">돼지/불고기/찜닭 양념</a></li>'
+'							<li><a href="#2">중식/양식/파스타 소스</a></li>'
+'							<li><a href="#2">수입소스 전용</a></li>'
+'							<li><a href="#2">식초</a></li>'
+'							<li><a href="#2">음용식초</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">조미료/설탕/소금</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">참깨</a></li>'
+'							<li><a href="#2">고춧가루</a></li>'
+'							<li><a href="#2">가공조미료</a></li>'
+'							<li><a href="#2">후추/향신료</a></li>'
+'							<li><a href="#2">액젓</a></li>'
+'							<li><a href="#2">설탕</a></li>'
+'							<li><a href="#2">물엿/올리고당</a></li>'
+'							<li><a href="#2">소금</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">유지류</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">식용류</a></li>'
+'							<li><a href="#2">참기름/들기름</a></li>'
+'							<li><a href="#2">올리브유</a></li>'
+'							<li><a href="#2">포도씨유</a></li>'
+'							<li><a href="#2">카놀라유/기타유</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">분유/유아식</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">남양분유</a></li>'
+'							<li><a href="#2">매일분유</a></li>'
+'							<li><a href="#2">일동분유</a></li>'
+'							<li><a href="#2">파스퇴르분유</a></li>'
+'							<li><a href="#2">아이배냇 산양유</a></li>'
+'							<li><a href="#2">기타 분유</a></li>'
+'							<li><a href="#2">이유식</a></li>'
+'							<li><a href="#2">유아간식/음료</a></li>'
+'							<li><a href="#2">영유아 두유</a></li>'
+'						</ul>'
+'					</li>'
+'				</ul>'
+'			</li>'
+'			<li><a href="#2">건강식품/친환경	</a>'
+'				<ul class="depth3">'
+'					<li><a href="#2">건강/다이어트 식품</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">홍삼/인삼</a></li>'
+'							<li><a href="#2">즙류(포도,석류 등)</a></li>'
+'							<li><a href="#2">꿀/조청</a></li>'
+'							<li><a href="#2">건강선물세트</a></li>'
+'							<li><a href="#2">다이어트 식품</a></li>'
+'							<li><a href="#2">비타민류</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">건강식품 브랜드</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">정관장-뿌리삼</a></li>'
+'							<li><a href="#2">정관장-농축액류</a></li>'
+'							<li><a href="#2">정관장-우리아이용</a></li>'
+'							<li><a href="#2">롯데 헬스원</a></li>'
+'							<li><a href="#2">종근당</a></li>'
+'							<li><a href="#2">세노비스</a></li>'
+'							<li><a href="#2">CJ 건강</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">친환경신선식품</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">쌀/잡곡</a></li>'
+'							<li><a href="#2">과일/견과류</a></li>'
+'							<li><a href="#2">채소</a></li>'
+'							<li><a href="#2">정육/계란</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">친환경가공식품</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">냉장냉동</a></li>'
+'							<li><a href="#2">통조림/쨈</a></li>'
+'							<li><a href="#2">과자</a></li>'
+'							<li><a href="#2">면/대용식</a></li>'
+'							<li><a href="#2">음료/건강식품</a></li>'
+'							<li><a href="#2">장류/소스류</a></li>'
+'						</ul>'
+'					</li>'
+'				</ul>'
+'			</li>'
+'			<li><a href="#2">커피/차/음료</a>'
+'				<ul class="depth3">'
+'					<li><a href="#2">커피</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">일반커피믹스</a></li>'
+'							<li><a href="#2">블랙/향커피믹스</a></li>'
+'							<li><a href="#2">리필/용기커피</a></li>'
+'							<li><a href="#2">아이스커피</a></li>'
+'							<li><a href="#2">티백원두커피</a></li>'
+'							<li><a href="#2">홀빈원두커피</a></li>'
+'							<li><a href="#2">분쇄원두커피</a></li>'
+'							<li><a href="#2">캡슐커피</a></li>'
+'							<li><a href="#2">커피크림</a></li>'
+'							<li><a href="#2">시럽/데코파우더</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">차</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">녹차/냉녹차</a></li>'
+'							<li><a href="#2">현미/기타 녹차</a></li>'
+'							<li><a href="#2">보리/옥수수차(식수용포함)</a></li>'
+'							<li><a href="#2">둥글레/메밀/결명/다이어트차</a></li>'
+'							<li><a href="#2">허브차/홍차/보이차</a></li>'
+'							<li><a href="#2">유자/모과/액상차</a></li>'
+'							<li><a href="#2">코코아</a></li>'
+'							<li><a href="#2">국산차(인삼/홍삼/생강)</a></li>'
+'							<li><a href="#2">분말곡물차(율무/땅콩/한방)</a></li>'
+'							<li><a href="#2">아이스티</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">생수/탄산/이온/차음료/무알콜</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">600ML 이하 생수</a></li>'
+'							<li><a href="#2">600ML 초과 생수</a></li>'
+'							<li><a href="#2">수입생수/탄산수</a></li>'
+'							<li><a href="#2">사이다/콜라 외 캔 탄산</a></li>'
+'							<li><a href="#2">사이다/콜라 외 Pet 탄산</a></li>'
+'							<li><a href="#2">비타민음료</a></li>'
+'							<li><a href="#2">이온/에너지음료</a></li>'
+'							<li><a href="#2">커피음료</a></li>'
+'							<li><a href="#2">냉장 커피음료</a></li>'
+'							<li><a href="#2">차음료</a></li>'
+'							<li><a href="#2">무알콜맥주</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">과즙음료</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">오렌지주스</a></li>'
+'							<li><a href="#2">포도주스</a></li>'
+'							<li><a href="#2">기타/야채주스</a></li>'
+'							<li><a href="#2">친환경음료</a></li>'
+'							<li><a href="#2">어린이음료</a></li>'
+'							<li><a href="#2">전통음료</a></li>'
+'							<li><a href="#2">음료 선물세트</a></li>'
+'							<li><a href="#2">수입음료</a></li>'
+'							<li><a href="#2">냉장 과즙음료</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">두유</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">일반두유</a></li>'
+'							<li><a href="#2">기능성/혼합두유</a></li>'
+'							<li><a href="#2">영유아두유</a></li>'
+'							<li><a href="#2">냉장두유</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">기능성/숙취해소음료</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">숙취해소음료</a></li>'
+'							<li><a href="#2">드링크제</a></li>'
+'							<li><a href="#2">기타 건강기능성 음료</a></li>'
+'						</ul>'
+'					</li>'
+'				</ul>'
+'			</li>'
+'			<li><a href="#2">과자</a>'
+'				<ul class="depth3">'
+'					<li><a href="#2">스낵/시리얼</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">일반스낵</a></li>'
+'							<li><a href="#2">감자/고구마스낵</a></li>'
+'							<li><a href="#2">쌀과자</a></li>'
+'							<li><a href="#2">옥수수스낵</a></li>'
+'							<li><a href="#2">팝콘/나초</a></li>'
+'							<li><a href="#2">어린이용 시리얼</a></li>'
+'							<li><a href="#2">성인/패밀리용 시리얼</a></li>'
+'							<li><a href="#2">수입 시리얼</a></li>'
+'							<li><a href="#2">안주류</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">쿠키/비스킷/파이</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">하드쿠키</a></li>'
+'							<li><a href="#2">소프트쿠키</a></li>'
+'							<li><a href="#2">비스킷/크래커</a></li>'
+'							<li><a href="#2">샌드</a></li>'
+'							<li><a href="#2">웨하스/와플</a></li>'
+'							<li><a href="#2">화과자/양갱/전통과자</a></li>'
+'							<li><a href="#2">맛밤류</a></li>'
+'							<li><a href="#2">초코쿠키/초코과자</a></li>'
+'							<li><a href="#2">파이/초코파이</a></li>'
+'							<li><a href="#2">카스타드/소프트케익류</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">사탕/캬라멜/껌/쨈</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">하드캔드</a></li>'
+'							<li><a href="#2">스틱/막대캔디</a></li>'
+'							<li><a href="#2">캬라멜</a></li>'
+'							<li><a href="#2">젤리</a></li>'
+'							<li><a href="#2">껌</a></li>'
+'							<li><a href="#2">쨈</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">초콜릿/빼빼로</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">판 초콜릿(가나 외)</a></li>'
+'							<li><a href="#2">쉘 초콜릿(ABC 외)</a></li>'
+'							<li><a href="#2">바 초콜릿(스니커즈 외)</a></li>'
+'							<li><a href="#2">빼빼로/가공초콜릿</a></li>'
+'							<li><a href="#2">수입초콜릿/캔디</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">떡/빵/베이커리</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">손큰피자</a></li>'
+'							<li><a href="#2">떡류</a></li>'
+'							<li><a href="#2">빵/찐빵/호두과자</a></li>'
+'							<li><a href="#2">식빵</a></li>'
+'							<li><a href="#2">냉동생지/냉동빵</a></li>'
+'							<li><a href="#2">선물용 배달 케익</a></li>'
+'						</ul>'
+'					</li>'
+'				</ul>'
+'			</li>'
+'		</ul>'
+'	</li>'
+'	<li class="menu2_2"><a href="#1"><span>생활/패션</span></a>'
+'		<ul class="depth2" style="display:none;">'
+'			<li><a href="#2">유아/출산용품</a>'
+'				<ul class="depth3">'
+'					<li><a href="#2">임부용품/출산용품</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">임부용잡화/보호대/기타용품</a></li>'
+'							<li><a href="#2">임부용 스킨케어</a></li>'
+'							<li><a href="#2">출산선물세트</a></li>'
+'							<li><a href="#2">손수건/턱받이</a></li>'
+'							<li><a href="#2">속겉싸개/손발싸개</a></li>'
+'							<li><a href="#2">이불/방수요/베개</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">분유/유아식</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">남양분유</a></li>'
+'							<li><a href="#2">매일분유</a></li>'
+'							<li><a href="#2">일동분유</a></li>'
+'							<li><a href="#2">파스퇴르분유</a></li>'
+'							<li><a href="#2">아이배냇 산양유</a></li>'
+'							<li><a href="#2">기타 분유</a></li>'
+'							<li><a href="#2">이유식</a></li>'
+'							<li><a href="#2">유아간식/음료</a></li>'
+'							<li><a href="#2">영유아 두유</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">기저귀/물티슈</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">10Kg 이상</a></li>'
+'							<li><a href="#2">10Kg이하/소포장</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">산지무료배송</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">하기스</a></li>'
+'							<li><a href="#2">보솜이</a></li>'
+'							<li><a href="#2">마미포코/토디앙</a></li>'
+'							<li><a href="#2">군기저귀</a></li>'
+'							<li><a href="#2">수입기저귀</a></li>'
+'							<li><a href="#2">일자형기저귀</a></li>'
+'							<li><a href="#2">테이프형기저귀</a></li>'
+'							<li><a href="#2">팬티형기저귀</a></li>'
+'							<li><a href="#2">유아물티슈</a></li>'
+'							<li><a href="#2">성인용기저귀</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">목욕/세제/스킨케어/안전용품</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">유아욕조/목욕용품</a></li>'
+'							<li><a href="#2">유아비누/샴푸/바스</a></li>'
+'							<li><a href="#2">유아로션/크림/밤</a></li>'
+'							<li><a href="#2">유아썬크림</a></li>'
+'							<li><a href="#2">유아파우더/오일</a></li>'
+'							<li><a href="#2">유아세정/세제류</a></li>'
+'							<li><a href="#2">유아치약/칫솔</a></li>'
+'							<li><a href="#2">유아변기</a></li>'
+'							<li><a href="#2">체온계/흡입기</a></li>'
+'							<li><a href="#2">의료/소독기/기타위생용품</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">수유/이유용품</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">유축기</a></li>'
+'							<li><a href="#2">젖병</a></li>'
+'							<li><a href="#2">젖꼭지</a></li>'
+'							<li><a href="#2">젖병솔/집게/소독용품</a></li>'
+'							<li><a href="#2">모유수유패드/쿠션</a></li>'
+'							<li><a href="#2">저장팩/케이스</a></li>'
+'							<li><a href="#2">물통/물병/보온병</a></li>'
+'							<li><a href="#2">수유/보조용품</a></li>'
+'							<li><a href="#2">유아조리/식기</a></li>'
+'							<li><a href="#2">이유식컵/부속품</a></li>'
+'							<li><a href="#2">젖병소독기/건조기</a></li>'
+'							<li><a href="#2">턱받이/기타출산용품</a></li>'
+'							<li><a href="#2">치발기/노리개/모빌</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">유모차/카시트/기구</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">유모차</a></li>'
+'							<li><a href="#2">카시트</a></li>'
+'							<li><a href="#2">아기띠/캐리어/포대기</a></li>'
+'							<li><a href="#2">보행기</a></li>'
+'							<li><a href="#2">바운서/침대</a></li>'
+'							<li><a href="#2">놀이방매트</a></li>'
+'							<li><a href="#2">유아식탁의자</a></li>'
+'							<li><a href="#2">유아의자/책상/유아쇼파</a></li>'
+'							<li><a href="#2">정리대/정리함</a></li>'
+'							<li><a href="#2">모빌/자전거/장난감</a></li>'
+'						</ul>'
+'					</li>'
+'				</ul>'
+'			</li>'
+'			<li><a href="#2">유아동패션/잡화</a>'
+'				<ul class="depth3">'
+'					<li><a href="#2">유아동의류</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">저고리/바디수트/우주복</a></li>'
+'							<li><a href="#2">남아동정장/상하복세트</a></li>'
+'							<li><a href="#2">남아동티셔츠/후드</a></li>'
+'							<li><a href="#2">남아동셔츠</a></li>'
+'							<li><a href="#2">남아동바지</a></li>'
+'							<li><a href="#2">여아동정장/상하복세트</a></li>'
+'							<li><a href="#2">여아동자켓/점퍼</a></li>'
+'							<li><a href="#2">여아동티셔츠/후드</a></li>'
+'							<li><a href="#2">여아동셔츠</a></li>'
+'							<li><a href="#2">여아동원피스</a></li>'
+'							<li><a href="#2">여아동바지/스커트</a></li>'
+'							<li><a href="#2">남아동한복</a></li>'
+'							<li><a href="#2">여아동한복</a></li>'
+'							<li><a href="#2">남아동수영복</a></li>'
+'							<li><a href="#2">여아동수영복</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">유아동언더웨어/양말</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">남아동팬티</a></li>'
+'							<li><a href="#2">남아동런링</a></li>'
+'							<li><a href="#2">남아동내의</a></li>'
+'							<li><a href="#2">여아동팬티</a></li>'
+'							<li><a href="#2">여아동런닝</a></li>'
+'							<li><a href="#2">여아동내의</a></li>'
+'							<li><a href="#2">여아동브라</a></li>'
+'							<li><a href="#2">유아동양말</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">유아동신발/가방/잡화</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">유아신발</a></li>'
+'							<li><a href="#2">남아동신발</a></li>'
+'							<li><a href="#2">여아동신발</a></li>'
+'							<li><a href="#2">아동가방</a></li>'
+'							<li><a href="#2">아동모자/장갑</a></li>'
+'							<li><a href="#2">아동밸트/기타잡화</a></li>'
+'						</ul>'
+'					</li>'
+'				</ul>'
+'			</li>'
+'			<li><a href="#2">세제/위생</a>'
+'				<ul class="depth3">'
+'					<li><a href="#2">세탁세제</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">가루세제-일반</a></li>'
+'							<li><a href="#2">가루세제-드럼</a></li>'
+'							<li><a href="#2">액체세제-일반</a></li>'
+'							<li><a href="#2">액체세제-드럼</a></li>'
+'							<li><a href="#2">섬유유연제-일반</a></li>'
+'							<li><a href="#2">섬유유연제-드럼</a></li>'
+'							<li><a href="#2">울샴푸</a></li>'
+'							<li><a href="#2">세탁비누</a></li>'
+'							<li><a href="#2">세탁보조제</a></li>'
+'							<li><a href="#2">표백제</a></li>'
+'							<li><a href="#2">유아용세제</a></li>'
+'							<li><a href="#2">옥시크린</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">청소세제</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">제습제</a></li>'
+'							<li><a href="#2">욕실청소세제</a></li>'
+'							<li><a href="#2">다용도세정제</a></li>'
+'							<li><a href="#2">주방청소세제</a></li>'
+'							<li><a href="#2">곰팡이제거제</a></li>'
+'							<li><a href="#2">욕실청소세제</a></li>'
+'							<li><a href="#2">변기세정제</a></li>'
+'							<li><a href="#2">락스</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">방향/탈취/살충</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">섬유탈취제</a></li>'
+'							<li><a href="#2">주거탈취제</a></li>'
+'							<li><a href="#2">공기탈취제</a></li>'
+'							<li><a href="#2">방향제</a></li>'
+'							<li><a href="#2">방충제</a></li>'
+'							<li><a href="#2">파리모기살충제</a></li>'
+'							<li><a href="#2">바퀴개미살충제</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">화장지</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">2겹화장지</a></li>'
+'							<li><a href="#2">3겹화장지</a></li>'
+'							<li><a href="#2">미용티슈</a></li>'
+'							<li><a href="#2">여행용티슈</a></li>'
+'							<li><a href="#2">키친타올</a></li>'
+'							<li><a href="#2">아기물티슈</a></li>'
+'							<li><a href="#2">일반물티슈</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">생리대</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">소형</a></li>'
+'							<li><a href="#2">중형</a></li>'
+'							<li><a href="#2">대형</a></li>'
+'							<li><a href="#2">오버나이트</a></li>'
+'							<li><a href="#2">팬티라이너</a></li>'
+'							<li><a href="#2">생리대기획팩</a></li>'
+'							<li><a href="#2">삽입형생리대</a></li>'
+'							<li><a href="#2">성인용기저귀</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">구강용품</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">치약</a></li>'
+'							<li><a href="#2">칫솔</a></li>'
+'							<li><a href="#2">유아용치약</a></li>'
+'							<li><a href="#2">유아용칫솔</a></li>'
+'							<li><a href="#2">가글용품</a></li>'
+'							<li><a href="#2">치간칫솔</a></li>'
+'							<li><a href="#2">치약</a></li>'
+'							<li><a href="#2">여행용세트/기타</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">개인위생용품</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">밴드/마스크/의약외품</a></li>'
+'							<li><a href="#2">렌즈관리용품</a></li>'
+'							<li><a href="#2">면도기</a></li>'
+'							<li><a href="#2">면도용품/젤</a></li>'
+'							<li><a href="#2">면도날</a></li>'
+'							<li><a href="#2">여성용면도기</a></li>'
+'							<li><a href="#2">일회용면도기</a></li>'
+'						</ul>'
+'					</li>'
+'				</ul>'
+'			</li>'
+'			<li><a href="#2">헤어/바디/화장품</a>'
+'				<ul class="depth3">'
+'					<li><a href="#2">헤어용품/악세서리</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">샴푸</a></li>'
+'							<li><a href="#2">모근강화샴푸</a></li>'
+'							<li><a href="#2">린스</a></li>'
+'							<li><a href="#2">모근강화린스</a></li>'
+'							<li><a href="#2">샴푸린스기획</a></li>'
+'							<li><a href="#2">모근강화샴푸기획</a></li>'
+'							<li><a href="#2">염색약</a></li>'
+'							<li><a href="#2">트리트먼트/헤어팩</a></li>'
+'							<li><a href="#2">헤어세럼/에센스</a></li>'
+'							<li><a href="#2">헤어스타일링</a></li>'
+'							<li><a href="#2">헤어핀/헤어밴드</a></li>'
+'							<li><a href="#2">헤어브러쉬/헤어롤</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">세안/바디/핸드/풋케어</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">비누</a></li>'
+'							<li><a href="#2">립/아이리무버</a></li>'
+'							<li><a href="#2">훼이셜클렌저/크림</a></li>'
+'							<li><a href="#2">바디클렌저</a></li>'
+'							<li><a href="#2">바디로션</a></li>'
+'							<li><a href="#2">바디워시</a></li>'
+'							<li><a href="#2">핸드풋크림/케어용품</a></li>'
+'							<li><a href="#2">데오도란트</a></li>'
+'							<li><a href="#2">제모제</a></li>'
+'							<li><a href="#2">바디/태닝오일</a></li>'
+'							<li><a href="#2">훼이셜/바디스크럽</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">화장품</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">스킨</a></li>'
+'							<li><a href="#2">로션</a></li>'
+'							<li><a href="#2">아이크림</a></li>'
+'							<li><a href="#2">세럼/엠플/에센스</a></li>'
+'							<li><a href="#2">선크림/로션</a></li>'
+'							<li><a href="#2">마스크/팩/마사지크림</a></li>'
+'							<li><a href="#2">미스트</a></li>'
+'							<li><a href="#2">립케어</a></li>'
+'							<li><a href="#2">훼이셜오일</a></li>'
+'							<li><a href="#2">남성화장품</a></li>'
+'							<li><a href="#2">화장품세트</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">메이크업/화장솜/네일</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">베이스메이크업</a></li>'
+'							<li><a href="#2">색조메이크업</a></li>'
+'							<li><a href="#2">화장솜/면봉</a></li>'
+'							<li><a href="#2">네일용품</a></li>'
+'							<li><a href="#2">화장소품/이미용품</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">향수</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">여성향수</a></li>'
+'							<li><a href="#2">남성향수</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">브랜드별 화장품</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">과일나라</a></li>'
+'							<li><a href="#2">가스비</a></li>'
+'							<li><a href="#2">네이처리퍼블릭</a></li>'
+'							<li><a href="#2">더마이</a></li>'
+'							<li><a href="#2">더페이스샵</a></li>'
+'							<li><a href="#2">라끄베르</a></li>'
+'							<li><a href="#2">로레알</a></li>'
+'							<li><a href="#2">로베아</a></li>'
+'							<li><a href="#2">리스킨</a></li>'
+'							<li><a href="#2">마몽드</a></li>'
+'							<li><a href="#2">보닌</a></li>'
+'							<li><a href="#2">빅토리아 스웨덴</a></li>'
+'							<li><a href="#2">수려한</a></li>'
+'							<li><a href="#2">스킨푸드</a></li>'
+'							<li><a href="#2">아이오페</a></li>'
+'							<li><a href="#2">엘리자베스아덴</a></li>'
+'							<li><a href="#2">이니스프리</a></li>'
+'							<li><a href="#2">오딧세이/미래파</a></li>'
+'							<li><a href="#2">오르비스</a></li>'
+'							<li><a href="#2">오이보스</a></li>'
+'							<li><a href="#2">올레이</a></li>'
+'							<li><a href="#2">이자녹스</a></li>'
+'							<li><a href="#2">지아자</a></li>'
+'							<li><a href="#2">치크룸</a></li>'
+'							<li><a href="#2">한율</a></li>'
+'							<li><a href="#2">해피바스</a></li>'
+'							<li><a href="#2">기타브랜드</a></li>'
+'						</ul>'
+'					</li>'
+'				</ul>'
+'			</li>'
+'			<li><a href="#2">홈인테리어</a>'
+'				<ul class="depth3">'
+'					<li><a href="#2">가구</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">침실가구</a></li>'
+'							<li><a href="#2">거실장/TV장</a></li>'
+'							<li><a href="#2">소파</a></li>'
+'							<li><a href="#2">식탁</a></li>'
+'							<li><a href="#2">주방수납장/렌지대</a></li>'
+'							<li><a href="#2">다용도상/교자상</a></li>'
+'							<li><a href="#2">다용도테이블</a></li>'
+'							<li><a href="#2">수납가구</a></li>'
+'							<li><a href="#2">책상</a></li>'
+'							<li><a href="#2">책장</a></li>'
+'							<li><a href="#2">의자</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">침구/커튼</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">침대커버세트</a></li>'
+'							<li><a href="#2">요/매트</a></li>'
+'							<li><a href="#2">차렵이불</a></li>'
+'							<li><a href="#2">베개</a></li>'
+'							<li><a href="#2">쿠션</a></li>'
+'							<li><a href="#2">패드</a></li>'
+'							<li><a href="#2">커튼</a></li>'
+'							<li><a href="#2">커튼악세서리</a></li>'
+'							<li><a href="#2">시즌상품</a></li>'
+'							<li><a href="#2">카페트/러그</a></li>'
+'							<li><a href="#2">유아동침구</a></li>'
+'							<li><a href="#2">이불솜/속통</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">수납용품</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">메탈렉</a></li>'
+'							<li><a href="#2">고정식행거</a></li>'
+'							<li><a href="#2">이동식행거</a></li>'
+'							<li><a href="#2">바구니</a></li>'
+'							<li><a href="#2">리빙박스</a></li>'
+'							<li><a href="#2">종이수납함</a></li>'
+'							<li><a href="#2">공간박스/수납소품</a></li>'
+'							<li><a href="#2">플라스틱 서랍장</a></li>'
+'							<li><a href="#2">압축팩/커버</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">인테리어소품</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">벽시계</a></li>'
+'							<li><a href="#2">탁상시계</a></li>'
+'							<li><a href="#2">액자</a></li>'
+'							<li><a href="#2">거울</a></li>'
+'							<li><a href="#2">일반시트지</a></li>'
+'							<li><a href="#2">데코시트지</a></li>'
+'							<li><a href="#2">패브릭</a></li>'
+'							<li><a href="#2">기타소품</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2"> DIY/보수용품</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">페인트</a></li>'
+'							<li><a href="#2">안전용품</a></li>'
+'							<li><a href="#2">멀티탭(2~3구)</a></li>'
+'							<li><a href="#2">멀티탭(4~6구)</a></li>'
+'							<li><a href="#2">스위치/콘센트</a></li>'
+'							<li><a href="#2">전기선</a></li>'
+'							<li><a href="#2">기타보수용품</a></li>'
+'							<li><a href="#2">후크류</a></li>'
+'							<li><a href="#2">접착제</a></li>'
+'							<li><a href="#2">일반공구</a></li>'
+'							<li><a href="#2">전동공구</a></li>'
+'							<li><a href="#2">자물쇠/철물</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">건전지/조명/전구</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">AA건전지</a></li>'
+'							<li><a href="#2">AAA건전지</a></li>'
+'							<li><a href="#2">충전지/특수건전지</a></li>'
+'							<li><a href="#2">인버터스탠드</a></li>'
+'							<li><a href="#2">장식스탠드</a></li>'
+'							<li><a href="#2">등기구</a></li>'
+'							<li><a href="#2">형광등</a></li>'
+'							<li><a href="#2">컴팩트 전구</a></li>'
+'							<li><a href="#2">취침등</a></li>'
+'							<li><a href="#2">후레쉬/랜턴</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">원예/꽃배달</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">꽃배달</a></li>'
+'							<li><a href="#2">화분</a></li>'
+'							<li><a href="#2">화분받침</a></li>'
+'							<li><a href="#2">원예공구</a></li>'
+'							<li><a href="#2">원예소품</a></li>'
+'							<li><a href="#2">영양제</a></li>'
+'							<li><a href="#2">조화</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">모기장/대자리</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">모기장</a></li>'
+'							<li><a href="#2">대자리</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">이케아(IKEA)</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">거실가구</a></li>'
+'							<li><a href="#2">침실가구</a></li>'
+'							<li><a href="#2">학생가구</a></li>'
+'							<li><a href="#2">주방가구</a></li>'
+'							<li><a href="#2">인테리어가구</a></li>'
+'							<li><a href="#2">기타소품/가구</a></li>'
+'							<li><a href="#2">주방식기</a></li>'
+'							<li><a href="#2">주방잡화/기타</a></li>'
+'							<li><a href="#2">생활수납용품</a></li>'
+'							<li><a href="#2">기타 생활용품</a></li>'
+'							<li><a href="#2">침구류</a></li>'
+'							<li><a href="#2">러그/커튼/패브릭 기타</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">디자인/생활매트</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">파크론 놀이방매트</a></li>'
+'							<li><a href="#2">LG하우시스 놀이방매트</a></li>'
+'							<li><a href="#2">파크론 디자인매트</a></li>'
+'							<li><a href="#2">LG하우시스 디자인매트</a></li>'
+'							<li><a href="#2">놀이방매트</a></li>'
+'							<li><a href="#2">디자인매트</a></li>'
+'							<li><a href="#2">생활매트</a></li>'
+'							<li><a href="#2">캠핑/야외용매트</a></li>'
+'						</ul>'
+'					</li>'
+'				</ul>'
+'			</li>'
+'			<li><a href="#2">주방/청소용품</a>'
+'				<ul class="depth3">'
+'					<li><a href="#2">그릇/수저</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">수저/수저통</a></li>'
+'							<li><a href="#2">아동용수저</a></li>'
+'							<li><a href="#2">티스푼/포크/나이프</a></li>'
+'							<li><a href="#2">공기</a></li>'
+'							<li><a href="#2">대접/면기</a></li>'
+'							<li><a href="#2">접시</a></li>'
+'							<li><a href="#2">볼/종지</a></li>'
+'							<li><a href="#2">찬기</a></li>'
+'							<li><a href="#2">브랜드도자기</a></li>'
+'							<li><a href="#2">유아식기</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">컵/용품</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">커피잔</a></li>'
+'							<li><a href="#2">여과지/드리퍼/포트</a></li>'
+'							<li><a href="#2">유리잔</a></li>'
+'							<li><a href="#2">머그잔</a></li>'
+'							<li><a href="#2">와인잔</a></li>'
+'							<li><a href="#2">와인스크류/오프너</a></li>'
+'							<li><a href="#2">아동용컵</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">조리기구</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">후라이팬(미니-24cm)</a></li>'
+'							<li><a href="#2">후라이팬(26~32cm)</a></li>'
+'							<li><a href="#2">구이팬/궁중팬/양면팬</a></li>'
+'							<li><a href="#2">편수냄비</a></li>'
+'							<li><a href="#2">양수냄비</a></li>'
+'							<li><a href="#2">전골냄비</a></li>'
+'							<li><a href="#2">뚝배기</a></li>'
+'							<li><a href="#2">압력솥</a></li>'
+'							<li><a href="#2">곰솥/들통</a></li>'
+'							<li><a href="#2">주전자</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">조리도구</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">국자</a></li>'
+'							<li><a href="#2">뒤지개</a></li>'
+'							<li><a href="#2">요리스푼/집게/기타</a></li>'
+'							<li><a href="#2">믹싱볼/양푼</a></li>'
+'							<li><a href="#2">주방가위</a></li>'
+'							<li><a href="#2">식/과도</a></li>'
+'							<li><a href="#2">채칼/감자칼</a></li>'
+'							<li><a href="#2">도마</a></li>'
+'							<li><a href="#2">목기</a></li>'
+'							<li><a href="#2">제빵용품</a></li>'
+'							<li><a href="#2">쟁반</a></li>'
+'							<li><a href="#2">채반/바구니</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">밀폐/보관용기</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">락앤락</a></li>'
+'							<li><a href="#2">글라스락</a></li>'
+'							<li><a href="#2">지퍼락</a></li>'
+'							<li><a href="#2">밀폐용기</a></li>'
+'							<li><a href="#2">양념통/소스병</a></li>'
+'							<li><a href="#2">저장용기</a></li>'
+'							<li><a href="#2">물병</a></li>'
+'							<li><a href="#2">아동물병</a></li>'
+'							<li><a href="#2">도시락/찬합</a></li>'
+'							<li><a href="#2">보온/보냉병</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">주방정리용품</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">주방선반</a></li>'
+'							<li><a href="#2">씽크대소품</a></li>'
+'							<li><a href="#2">식탁매트</a></li>'
+'							<li><a href="#2">수세미</a></li>'
+'							<li><a href="#2">행주</a></li>'
+'							<li><a href="#2">고무장갑</a></li>'
+'							<li><a href="#2">씽크매트/다용도매트</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">일회용품/소모품</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">호일</a></li>'
+'							<li><a href="#2">랩</a></li>'
+'							<li><a href="#2">지퍼백</a></li>'
+'							<li><a href="#2">비닐백</a></li>'
+'							<li><a href="#2">비닐장갑</a></li>'
+'							<li><a href="#2">종이컵</a></li>'
+'							<li><a href="#2">일회용품</a></li>'
+'							<li><a href="#2">일회용젓가락/수저</a></li>'
+'							<li><a href="#2">기타잡화</a></li>'
+'							<li><a href="#2">계절/나들이용품</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">청소용품</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">휴지통</a></li>'
+'							<li><a href="#2">밀대청소기</a></li>'
+'							<li><a href="#2">걸레/청소포</a></li>'
+'							<li><a href="#2">청소용솔/브러쉬</a></li>'
+'							<li><a href="#2">테이프크리너</a></li>'
+'							<li><a href="#2">종량제봉투</a></li>'
+'							<li><a href="#2">기타청소용품</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">세탁용품</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">세탁건조대</a></li>'
+'							<li><a href="#2">옷걸이</a></li>'
+'							<li><a href="#2">다리미판</a></li>'
+'							<li><a href="#2">세탁바구니</a></li>'
+'							<li><a href="#2">세탁망</a></li>'
+'							<li><a href="#2">빨래판/빨래집게</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">욕실용품</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">타월</a></li>'
+'							<li><a href="#2">샤워타월</a></li>'
+'							<li><a href="#2">매트</a></li>'
+'							<li><a href="#2">욕실장/선반</a></li>'
+'							<li><a href="#2">변기커버</a></li>'
+'							<li><a href="#2">욕실화</a></li>'
+'							<li><a href="#2">발판</a></li>'
+'							<li><a href="#2">휴지걸이/흡착용품</a></li>'
+'							<li><a href="#2">수도용품</a></li>'
+'							<li><a href="#2">대야/바가지</a></li>'
+'							<li><a href="#2">양치컵/비누받침</a></li>'
+'							<li><a href="#2">샤워커튼</a></li>'
+'						</ul>'
+'					</li>'
+'				</ul>'
+'			</li>'
+'			<li><a href="#2">문구/사무/자동차</a>'
+'				<ul class="depth3">'
+'					<li><a href="#2">미술용품</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">스케치북</a></li>'
+'							<li><a href="#2">색종이</a></li>'
+'							<li><a href="#2">미술도구류</a></li>'
+'							<li><a href="#2">미술재료류</a></li>'
+'							<li><a href="#2">물감/포스터칼라</a></li>'
+'							<li><a href="#2">색연필</a></li>'
+'							<li><a href="#2">사인펜</a></li>'
+'							<li><a href="#2">점토찰흙</a></li>'
+'							<li><a href="#2">서예도구</a></li>'
+'							<li><a href="#2">기타교보재</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">악기</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">건반악기</a></li>'
+'							<li><a href="#2">관악기</a></li>'
+'							<li><a href="#2">현악기</a></li>'
+'							<li><a href="#2">교재용악기</a></li>'
+'							<li><a href="#2">악기용교보재</a></li>'
+'							<li><a href="#2">멜로디혼/실로폰</a></li>'
+'							<li><a href="#2">리듬세트/리코오더</a></li>'
+'							<li><a href="#2">기타</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">노트</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">초등노트</a></li>'
+'							<li><a href="#2">중고노트</a></li>'
+'							<li><a href="#2">스프링/인덱스노트</a></li>'
+'							<li><a href="#2">기타일반노트</a></li>'
+'							<li><a href="#2">수첩/메모</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">필기도구</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">연필</a></li>'
+'							<li><a href="#2">볼펜/사인펜</a></li>'
+'							<li><a href="#2">유성매직/보드마카</a></li>'
+'							<li><a href="#2">필통</a></li>'
+'							<li><a href="#2">연필깎이</a></li>'
+'							<li><a href="#2">샤프/샤프심</a></li>'
+'							<li><a href="#2">지우개/수정액</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">사무용품</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">물풀/고체풀</a></li>'
+'							<li><a href="#2">접착제/테이프</a></li>'
+'							<li><a href="#2">견출지/포스트잇</a></li>'
+'							<li><a href="#2">보드/게시판</a></li>'
+'							<li><a href="#2">서식지/봉투</a></li>'
+'							<li><a href="#2">복사지/라벨지</a></li>'
+'							<li><a href="#2">펀치/스템플러</a></li>'
+'							<li><a href="#2">칼/가위</a></li>'
+'							<li><a href="#2">계산기</a></li>'
+'							<li><a href="#2">크립/집게/핀</a></li>'
+'							<li><a href="#2">기타OA용품</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">사무정리용품</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">책꽂이/화일박스</a></li>'
+'							<li><a href="#2">독서대</a></li>'
+'							<li><a href="#2">서류함/서류받침</a></li>'
+'							<li><a href="#2">클리어화일</a></li>'
+'							<li><a href="#2">바인더</a></li>'
+'							<li><a href="#2">기타화일</a></li>'
+'							<li><a href="#2">앨범</a></li>'
+'							<li><a href="#2">기타정리용품</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">팬시/파티용품</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">풍선</a></li>'
+'							<li><a href="#2">불꽃놀이</a></li>'
+'							<li><a href="#2">기타파티소품</a></li>'
+'							<li><a href="#2">포장지/쇼핑백</a></li>'
+'							<li><a href="#2">포장용품</a></li>'
+'							<li><a href="#2">팬시스티커</a></li>'
+'							<li><a href="#2">향초</a></li>'
+'							<li><a href="#2">편지지</a></li>'
+'							<li><a href="#2">기타팬시용품</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">도서</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">아동서적</a></li>'
+'							<li><a href="#2">아동전집</a></li>'
+'							<li><a href="#2">임신/육아</a></li>'
+'							<li><a href="#2">음반/CD</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">자동차용품</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">정비용품/와이퍼</a></li>'
+'							<li><a href="#2">연료첨가제/엔진오일</a></li>'
+'							<li><a href="#2">컴파운드/페인트</a></li>'
+'							<li><a href="#2">청소용품/도구</a></li>'
+'							<li><a href="#2">왁스/세정제</a></li>'
+'							<li><a href="#2">방향제</a></li>'
+'							<li><a href="#2">시트/쿠션</a></li>'
+'							<li><a href="#2">수납/핸드폰소품</a></li>'
+'							<li><a href="#2">핸들커버/파워핸들</a></li>'
+'							<li><a href="#2">룸미러/보조미러</a></li>'
+'							<li><a href="#2">기타악세서리</a></li>'
+'						</ul>'
+'					</li>'
+'				</ul>'
+'			</li>'
+'			<li><a href="#2">애완용품</a>'
+'				<ul class="depth3">'
+'					<li><a href="#2">애견식품</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">브랜드사료</a></li>'
+'							<li><a href="#2">연령/기능별사료</a></li>'
+'							<li><a href="#2">간식/영양제</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">애견용품</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">목욕용품</a></li>'
+'							<li><a href="#2">미용용품</a></li>'
+'							<li><a href="#2">배변용품</a></li>'
+'							<li><a href="#2">애견줄</a></li>'
+'							<li><a href="#2">의류/엑세서리</a></li>'
+'							<li><a href="#2">장난감식기</a></li>'
+'							<li><a href="#2">하우스/이동장</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">고양이식품</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">브랜드사료</a></li>'
+'							<li><a href="#2">연령/기능별사료</a></li>'
+'							<li><a href="#2">캔/파우치</a></li>'
+'							<li><a href="#2">간식/영양제</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">고양이용품</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">모래</a></li>'
+'							<li><a href="#2">화장실</a></li>'
+'							<li><a href="#2">장난감/캣닙</a></li>'
+'							<li><a href="#2">스크래쳐/캣타워</a></li>'
+'							<li><a href="#2">목욕/미용</a></li>'
+'							<li><a href="#2">하우스/캐리어</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">수족관/기타동물</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">관상어</a></li>'
+'							<li><a href="#2">관상조</a></li>'
+'							<li><a href="#2">애완곤충용품</a></li>'
+'							<li><a href="#2">애완소동물</a></li>'
+'							<li><a href="#2">기타용품</a></li>'
+'						</ul>'
+'					</li>'
+'				</ul>'
+'			</li>'
+'			<li><a href="#2">패션의류/언더웨어</a>'
+'				<ul class="depth3">'
+'					<li><a href="#2">남성의류</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">남성자켓</a></li>'
+'							<li><a href="#2">남성점퍼</a></li>'
+'							<li><a href="#2">남성카디건/조끼</a></li>'
+'							<li><a href="#2">남성니트</a></li>'
+'							<li><a href="#2">남성티셔츠</a></li>'
+'							<li><a href="#2">남성셔츠</a></li>'
+'							<li><a href="#2">남성바지</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">여성의류</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">여성자켓</a></li>'
+'							<li><a href="#2">여성점퍼</a></li>'
+'							<li><a href="#2">여성카디건/조끼</a></li>'
+'							<li><a href="#2">여성니트</a></li>'
+'							<li><a href="#2">여성티셔츠</a></li>'
+'							<li><a href="#2">여성셔츠/블라우스</a></li>'
+'							<li><a href="#2">여성원피스</a></li>'
+'							<li><a href="#2">여성스커트</a></li>'
+'							<li><a href="#2">여성바지</a></li>'
+'							<li><a href="#2">임부복</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">아동의류</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">남아동정장/상하복세트</a></li>'
+'							<li><a href="#2">남아동자켓/점퍼</a></li>'
+'							<li><a href="#2">남아동티셔츠/후드</a></li>'
+'							<li><a href="#2">남아동셔츠</a></li>'
+'							<li><a href="#2">남아동바지</a></li>'
+'							<li><a href="#2">여아동자켓/점퍼</a></li>'
+'							<li><a href="#2">여아동티셔츠/후드</a></li>'
+'							<li><a href="#2">여아동셔츠</a></li>'
+'							<li><a href="#2">여아동원피스</a></li>'
+'							<li><a href="#2">여아동바지/스커트</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">남성언더웨어</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">남성트렁크</a></li>'
+'							<li><a href="#2">남성삼각팬티</a></li>'
+'							<li><a href="#2">남성드로즈팬티</a></li>'
+'							<li><a href="#2">남성런닝/내의</a></li>'
+'							<li><a href="#2">남성잠옷/이지웨어</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">여성언더웨어</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">여성브라&세트</a></li>'
+'							<li><a href="#2">여성팬티</a></li>'
+'							<li><a href="#2">여성브라</a></li>'
+'							<li><a href="#2">여성런닝/내의</a></li>'
+'							<li><a href="#2">여성거들/보정쉐이퍼</a></li>'
+'							<li><a href="#2">여성잠옷/이지웨어</a></li>'
+'							<li><a href="#2">임부용속옷</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">아동언더웨어</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">남아동팬티</a></li>'
+'							<li><a href="#2">남아동런닝</a></li>'
+'							<li><a href="#2">남아동내의</a></li>'
+'							<li><a href="#2">여아동팬티</a></li>'
+'							<li><a href="#2">여아동런닝</a></li>'
+'							<li><a href="#2">여아동브라</a></li>'
+'							<li><a href="#2">여아동내의</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">양말/스타킹/레깅스</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">남성정장/캐쥬얼양말</a></li>'
+'							<li><a href="#2">남성스포츠양말</a></li>'
+'							<li><a href="#2">남성스니커즈양말</a></li>'
+'							<li><a href="#2">여성장장/캐쥬얼양말</a></li>'
+'							<li><a href="#2">여성스포츠양말</a></li>'
+'							<li><a href="#2">여성스니커즈양말</a></li>'
+'							<li><a href="#2">스타킹/레깅스/타이즈</a></li>'
+'							<li><a href="#2">아동양말/타이즈</a></li>'
+'						</ul>'
+'					</li>'
+'				</ul>'
+'			</li>'
+'			<li><a href="#2">신발/잡화</a>'
+'				<ul class="depth3">'
+'					<li><a href="#2">신발</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">남성구두</a></li>'
+'							<li><a href="#2">여성구두</a></li>'
+'							<li><a href="#2">남성운동화</a></li>'
+'							<li><a href="#2">여성운동화</a></li>'
+'							<li><a href="#2">아동화</a></li>'
+'							<li><a href="#2">슬리퍼</a></li>'
+'							<li><a href="#2">구두용품</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">지갑/밸트</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">남성지갑</a></li>'
+'							<li><a href="#2">여성지갑</a></li>'
+'							<li><a href="#2">남성밸트</a></li>'
+'							<li><a href="#2">여성밸트</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">여행가방</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">기내용소프트케이스</a></li>'
+'							<li><a href="#2">기내용하드케이스</a></li>'
+'							<li><a href="#2">수화물용소프트케이스</a></li>'
+'							<li><a href="#2">수화물용하드케이스</a></li>'
+'							<li><a href="#2">여행소품</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">핸드백/가방</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">토드백</a></li>'
+'							<li><a href="#2">숄더백</a></li>'
+'							<li><a href="#2">캐주얼백/백팩</a></li>'
+'							<li><a href="#2">서류가방/맨즈백</a></li>'
+'							<li><a href="#2">아동가방</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">패션악세서리/시즌잡화/우산</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">시계</a></li>'
+'							<li><a href="#2">선글라스</a></li>'
+'							<li><a href="#2">모자</a></li>'
+'							<li><a href="#2">장갑</a></li>'
+'							<li><a href="#2">넥타이</a></li>'
+'							<li><a href="#2">우산/우의</a></li>'
+'						</ul>'
+'					</li>'
+'				</ul>'
+'			</li>'
+'			<li><a href="#2">스포츠/레저</a>'
+'				<ul class="depth3">'
+'					<li><a href="#2">헬스기구/운동용품</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">런닝머신/실내사이클</a></li>'
+'							<li><a href="#2">아령/덤벨</a></li>'
+'							<li><a href="#2">줄넘기/짐볼/요가</a></li>'
+'							<li><a href="#2">훌라우프</a></li>'
+'							<li><a href="#2">체중계</a></li>'
+'							<li><a href="#2">헬스장갑/보호대</a></li>'
+'							<li><a href="#2">기타운동용품</a></li>'
+'							<li><a href="#2">요가복/트레이닝복</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">자전거</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">자전거</a></li>'
+'							<li><a href="#2">자전거부품/튜닝용품</a></li>'
+'							<li><a href="#2">자전거잠금/거치대/기타용품</a></li>'
+'							<li><a href="#2">헬멧/보호구/장갑/토시</a></li>'
+'							<li><a href="#2">자전거의류</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">등산</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">등산가방</a></li>'
+'							<li><a href="#2">등산화</a></li>'
+'							<li><a href="#2">등산스틱</a></li>'
+'							<li><a href="#2">등산모자</a></li>'
+'							<li><a href="#2">등산장갑/기타용품</a></li>'
+'							<li><a href="#2">남성등산자켓/조끼</a></li>'
+'							<li><a href="#2">남성등산티셔츠</a></li>'
+'							<li><a href="#2">남성등산바지</a></li>'
+'							<li><a href="#2">여성등산자켓/조끼</a></li>'
+'							<li><a href="#2">여성등산티셔츠</a></li>'
+'							<li><a href="#2">여성등산바지</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">캠핑</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">캠핑텐트/그늘막/소품</a></li>'
+'							<li><a href="#2">캠핑침낭/침대/매트</a></li>'
+'							<li><a href="#2">캠핑테이블</a></li>'
+'							<li><a href="#2">캠핑의자/야외용품</a></li>'
+'							<li><a href="#2">캠핑버너/그릴/스토치</a></li>'
+'							<li><a href="#2">캠핑코펠/취사도구/a></li>'
+'							<li><a href="#2">캠핑랜턴/램프/연료</a></li>'
+'							<li><a href="#2">캠핑기타용품</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">야구/축구</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">야구글러브</a></li>'
+'							<li><a href="#2">야구배트</a></li>'
+'							<li><a href="#2">야구공</a></li>'
+'							<li><a href="#2">야구기타용품</a></li>'
+'							<li><a href="#2">축구공</a></li>'
+'							<li><a href="#2">축구화</a></li>'
+'							<li><a href="#2">축구기타용품</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">농구/배구/탁구/배드민턴/테니스</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">농구</a></li>'
+'							<li><a href="#2">배구</a></li>'
+'							<li><a href="#2">탁구</a></li>'
+'							<li><a href="#2">테니스</a></li>'
+'							<li><a href="#2">배드민턴</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">골프</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">풀세트</a></li>'
+'							<li><a href="#2">드라이버</a></li>'
+'							<li><a href="#2">아이언</a></li>'
+'							<li><a href="#2">우드</a></li>'
+'							<li><a href="#2">유틸/하이브리드</a></li>'
+'							<li><a href="#2">퍼터</a></li>'
+'							<li><a href="#2">웨지/치퍼</a></li>'
+'							<li><a href="#2">골프공</a></li>'
+'							<li><a href="#2">골프장갑/모자</a></li>'
+'							<li><a href="#2">골프화</a></li>'
+'							<li><a href="#2">골프백/커버</a></li>'
+'							<li><a href="#2">골프연승용품</a></li>'
+'							<li><a href="#2">골프티/골프우산/기타용품</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">수영/스키보드</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">스키보드고글/장비</a></li>'
+'							<li><a href="#2">스키보드장갑/양말/기타</a></li>'
+'							<li><a href="#2">남성스키보드복</a></li>'
+'							<li><a href="#2">여성스키보드복</a></li>'
+'							<li><a href="#2">아동스키보드복</a></li>'
+'							<li><a href="#2">물놀이/수영용품</a></li>'
+'							<li><a href="#2">남성수영복</a></li>'
+'							<li><a href="#2">여성수영복</a></li>'
+'							<li><a href="#2">남아수영복</a></li>'
+'							<li><a href="#2">여아수영복</a></li>'
+'						</ul>'
+'					</li>'
+'				</ul>'
+'			</li>'
+'			<li><a href="#2">해외브랜드관</a>'
+'				<ul class="depth3">'
+'					<li><a href="#2">해외브랜드핸드백/가방/지갑</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">구찌(GUCCI)</a></li>'
+'							<li><a href="#2">끌로에(CHLOE)</a></li>'
+'							<li><a href="#2">더캠브리지사첼컴퍼니(THE CAMBRIDGE SATCHEL)</a></li>'
+'							<li><a href="#2">돌체앤가바나(DOLCE&GABBANA)</a></li>'
+'							<li><a href="#2">듀퐁(Dupont)</a></li>'
+'							<li><a href="#2">마이클코어스(Michael Kors)</a></li>'
+'							<li><a href="#2">마크제이콥스(MARC JACOBS)</a></li>'
+'							<li><a href="#2">멀버리(MULBERRY)</a></li>'
+'							<li><a href="#2">발리(BALLY)</a></li>'
+'							<li><a href="#2">버버리(BURBERRY)</a></li>'
+'							<li><a href="#2">보테가 베네타(bottegaveneta)</a></li>'
+'							<li><a href="#2">에트로(ETRO)</a></li>'
+'							<li><a href="#2">지방시(GIVENCHY)</a></li>'
+'							<li><a href="#2">키플링(kipling)</a></li>'
+'							<li><a href="#2">페라가모(FERRAGAMO)</a></li>'
+'							<li><a href="#2">펜디(FENDI)</a></li>'
+'							<li><a href="#2">폴스미스(PAUL SMITH)</a></li>'
+'							<li><a href="#2">프로엔자슐러(PROENZA SCHOULER)</a></li>'
+'							<li><a href="#2">기타브랜드</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">해외브랜드화장품/향수</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">엘리자베스 아덴(Elizabeth arden)</a></li>'
+'							<li><a href="#2">올레이(Olay)</a></li>'
+'							<li><a href="#2">로레알(Loreal)</a></li>'
+'							<li><a href="#2">비오템(BIOTHERM)</a></li>'
+'							<li><a href="#2">갸스비(GASTBY)</a></li>'
+'							<li><a href="#2">오이보스(EUBOS)</a></li>'
+'							<li><a href="#2">오르비스(Orbis)</a></li>'
+'							<li><a href="#2">로베아(LOVEA)</a></li>'
+'							<li><a href="#2">지아자(ZIAJA)</a></li>'
+'							<li><a href="#2">아로마베이비(Aroma Baby)</a></li>'
+'							<li><a href="#2">코린더팜(CORINE DE FARME)</a></li>'
+'							<li><a href="#2">불가리(Bulgari)</a></li>'
+'							<li><a href="#2">버버리(Burberry)</a></li>'
+'							<li><a href="#2">캘빈클레인(Calvin Klein) </a></li>'
+'							<li><a href="#2">랑방(Lanvin)</a></li>'
+'							<li><a href="#2">폴로랄프로렌(Polo Ralph Lauren) </a></li>'
+'							<li><a href="#2">인칸토/모스키노(MOSCHINO) </a></li>'
+'							<li><a href="#2">베르사체/안나수이/페레가모/지미추</a></li>'
+'							<li><a href="#2">빅토리아 에그팩</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">해외브랜드패션소품/선글라스</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">페라가모(FERRAGAMO)</a></li>'
+'							<li><a href="#2">펜디(FENDI)</a></li>'
+'							<li><a href="#2">비비안웨스트우드(Vivienne Westwood)</a></li>'
+'							<li><a href="#2">안나수이(ANNASUI)</a></li>'
+'							<li><a href="#2">구찌(GUCCI)</a></li>'
+'							<li><a href="#2">모스키노(MOSCHINO)</a></li>'
+'							<li><a href="#2">알비에로 마르티니(Alviero Martini)</a></li>'
+'							<li><a href="#2">캘빈클레인(Calvin Klein)</a></li>'
+'							<li><a href="#2">끌로에(CHLOE)</a></li>'
+'							<li><a href="#2">지방시(GIVENCHY)</a></li>'
+'							<li><a href="#2">마이클코어스(Michael Kors)</a></li>'
+'							<li><a href="#2">몽블랑(MONTBLANC)</a></li>'
+'							<li><a href="#2">스와로브스키(SWAROVSKI) </a></li>'
+'							<li><a href="#2">토즈(TODS)</a></li>'
+'							<li><a href="#2">타미힐피거(Tommy Hilfiger)</a></li>'
+'							<li><a href="#2">코치(Coach)</a></li>'
+'							<li><a href="#2">잭니클라우스(Jack Nicklaus)</a></li>'
+'							<li><a href="#2">에트로(ETRO)</a></li>'
+'							<li><a href="#2">칼 라거펠드 (Karl Lagerfeld)/기타</a></li>'
+'						</ul>'
+'					</li>'
+'				</ul>'
+'			</li>'
+'			<li><a href="#2">장난감</a>'
+'				<ul class="depth3">'
+'					<li><a href="#2">유아/레고/교육장난감</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">유아동 완구</a></li>'
+'							<li><a href="#2">피셔프라이스</a></li>'
+'							<li><a href="#2">리틀타익스</a></li>'
+'							<li><a href="#2">뽀로로</a></li>'
+'							<li><a href="#2">타요</a></li>'
+'							<li><a href="#2">로보카폴리</a></li>'
+'							<li><a href="#2">토마스</a></li>'
+'							<li><a href="#2">레고</a></li>'
+'							<li><a href="#2">메가블럭/플레이모빌</a></li>'
+'							<li><a href="#2">옥스포드/크레오</a></li>'
+'							<li><a href="#2">크레욜라/이젤</a></li>'
+'							<li><a href="#2">보드판/이젤</a></li>'
+'							<li><a href="#2">플레이도우/일반점토(클레이)</a></li>'
+'							<li><a href="#2">보드게임</a></li>'
+'							<li><a href="#2">클래식보드게임</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">남자아이 장난감</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">메탈베이</a></li>'
+'							<li><a href="#2">바쿠간</a></li>'
+'							<li><a href="#2">또봇</a></li>'
+'							<li><a href="#2">파워레인저</a></li>'
+'							<li><a href="#2">캐릭터장난감</a></li>'
+'							<li><a href="#2">자동차/기차</a></li>'
+'							<li><a href="#2">무선조종장난감(RC)</a></li>'
+'							<li><a href="#2">조립식장난감/건담/프라모델</a></li>'
+'							<li><a href="#2">폼건</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">여자아이 장난감</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">실바니안패밀리</a></li>'
+'							<li><a href="#2">펜디(FENDI)</a></li>'
+'							<li><a href="#2">뚱이/엔젤이/수집인형</a></li>'
+'							<li><a href="#2">똘똘이/달님이/콩순이</a></li>'
+'							<li><a href="#2">베렝구어/베이비얼라이브</a></li>'
+'							<li><a href="#2">미미/리틀미미</a></li>'
+'							<li><a href="#2">디즈니/쥬쥬/챠밍걸스</a></li>'
+'							<li><a href="#2">바비</a></li>'
+'							<li><a href="#2">주방/소꿉놀이</a></li>'
+'							<li><a href="#2">친환경인형</a></li>'
+'							<li><a href="#2">앵그리버드</a></li>'
+'							<li><a href="#2">뽀로로인형</a></li>'
+'							<li><a href="#2">캐릭터인형</a></li>'
+'							<li><a href="#2">동물인형</a></li>'
+'							<li><a href="#2">작동인형</a></li>'
+'						</ul>'
+'					</li>'
+'					<li><a href="#2">대형/승용/스포츠</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">볼풀/볼텐트</a></li>'
+'							<li><a href="#2">놀이집/플레이세트</a></li>'
+'							<li><a href="#2">스포츠장난감</a></li>'
+'							<li><a href="#2">자전거/킥보드/씽씽이</a></li>'
+'							<li><a href="#2">붕붕카/지붕차/웨곤</a></li>'
+'							<li><a href="#2">전동자동차/오토바이</a></li>'
+'							<li><a href="#2">시소/흔들말/그네</a></li>'
+'							<li><a href="#2">놀이터/체육관/미끄럼틀</a></li>'
+'						</ul>'
+'					</li>'
+'				</ul>'
+'			</li>'
+'		</ul>'
+'	</li>'
+'	<li class="menu2_3"><a href="#1"><span>가전</span></a>'
+'		<ul class="depth2" style="display:none;">'
+'			<li><a href="#2">하이마트 디지털가전</a>'
+'				<ul class="depth3">'
+'					<li><a href="#2">컴퓨터/주변기기/태블릿PC</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">데스크탑PC</a></li>'
+'							<li><a href="#2">데스크탑 + 모니터</a></li>'
+'							<li><a href="#2">노트북/넷북</a></li>'
+'							<li><a href="#2">태블릿PC</a></li>'
+'							<li><a href="#2">LCD/LED모니터</a></li>'
+'							<li><a href="#2">프린터/복합기/사무기기</a></li>'
+'							<li><a href="#2">닌텐도/XBOX/PS3/타이틀</a></li>'
+'							<li><a href="#2">컴퓨터주변기기</a></li>'
+'							<li><a href="#2">잉크/토너</a></li>'
+'						</ul></li>'
+'					<li><a href="#2">3D,LEDTV/LCD/PDP</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">3D / LED TV</a></li>'
+'							<li><a href="#2">LCD TV</a></li>'
+'							<li><a href="#2">PDP TV</a></li>'
+'							<li><a href="#2">장식장/셋탑박스</a></li>'
+'						</ul></li>'
+'					<li><a href="#2">디카/DSLR/캠코더</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">컴팩트/즉석카메라</a></li>'
+'							<li><a href="#2">하이엔드/미러리스</a></li>'
+'							<li><a href="#2">DSLR/마이크로포서드</a></li>'
+'							<li><a href="#2">캠코더</a></li>'
+'							<li><a href="#2">카메라 주변기기</a></li>'
+'						</ul></li>'
+'					<li><a href="#2"> MP3/PMP/네비/전자사전</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">MP3/MP4/주변기기</a></li>'
+'							<li><a href="#2">PMP/DMB/전자액자</a></li>'
+'							<li><a href="#2">네비게이션/하이패스/블랙박스</a></li>'
+'							<li><a href="#2">전자사전/어학기</a></li>'
+'						</ul></li>'
+'					<li><a href="#2">DVD/홈씨어터/오디오/이어폰</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">DVD/콤보/홈씨어터</a></li>'
+'							<li><a href="#2">ipod/iphone 도킹오디오</a></li>'
+'							<li><a href="#2">콤퍼넌트/카세트/CD카세트</a></li>'
+'							<li><a href="#2">AV 주변기기/테이프</a></li>'
+'							<li><a href="#2">이어폰/헤드폰</a></li>'
+'						</ul></li>'
+'					<li><a href="#2">휴대폰/전화기</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">휴대폰/주변기기</a></li>'
+'							<li><a href="#2">유ㆍ무선전화기/팩스</a></li>'
+'							<li><a href="#2">갤럭시 액세서리</a></li>'
+'							<li><a href="#2">옵티머스 액세서리</a></li>'
+'							<li><a href="#2">애플/아이폰 액세서리</a></li>'
+'							<li><a href="#2">베가 액세서리</a></li>'
+'							<li><a href="#2">휴대폰 Acc.샵</a></li>'
+'						</ul></li>'
+'				</ul></li>'
+'			<li><a href="#2">하이마트 대형 / 계절가전	</a>'
+'				<ul class="depth3">'
+'					<li><a href="#2">냉장고/김치냉장고</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">김치냉장고</a></li>'
+'							<li><a href="#2">양문형냉장고</a></li>'
+'							<li><a href="#2">일반형냉장고</a></li>'
+'							<li><a href="#2">와인셀러</a></li>'
+'							<li><a href="#2">업소형냉장고/냉동고</a></li>'
+'						</ul></li>'
+'					<li><a href="#2">세탁기/건조기</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">드럼세탁기</a></li>'
+'							<li><a href="#2">일반세탁기</a></li>'
+'							<li><a href="#2">건조기</a></li>'
+'						</ul></li>'
+'					<li><a href="#2">에어컨/제습기/선풍기</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">멀티 에어컨</a></li>'
+'							<li><a href="#2">스탠드 에어컨</a></li>'
+'							<li><a href="#2">벽걸이 에어컨</a></li>'
+'							<li><a href="#2">제습기</a></li>'
+'							<li><a href="#2">선풍기</a></li>'
+'							<li><a href="#2">쿨매트/해충퇴치기/살충기</a></li>'
+'							<li><a href="#2">가습기/에어워셔</a></li>'
+'							<li><a href="#2">냉/난방기</a></li>'
+'						</ul></li>'
+'				</ul></li>'
+'			<li><a href="#2">하이마트 생활 / 주방소형가전</a>'
+'				<ul class="depth3">'
+'					<li><a href="#2">주방/소형가전</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">전기압력밥솥/전기밥솥/일반압력솥</a></li>'
+'							<li><a href="#2">수납장/쌀독</a></li>'
+'							<li><a href="#2">전기/전자레인지</a></li>'
+'							<li><a href="#2">가스레인지/가스오븐</a></li>'
+'							<li><a href="#2">식기세척기/건조기/음식물처리기</a></li>'
+'							<li><a href="#2">커피메이커/토스터/전기포트</a></li>'
+'							<li><a href="#2">전기그릴/전기팬/튀김기</a></li>'
+'							<li><a href="#2">믹서기/녹즙기/빙수기</a></li>'
+'							<li><a href="#2">레인지후드렌탈</a></li>'
+'						</ul></li>'
+'					<li><a href="#2">생활가전/건강가전</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">청소기</a></li>'
+'							<li><a href="#2">디지털도어락</a></li>'
+'							<li><a href="#2">다리미</a></li>'
+'							<li><a href="#2">면도기</a></li>'
+'							<li><a href="#2">헤어케어</a></li>'
+'							<li><a href="#2">스탠드/전등/전자계산기</a></li>'
+'							<li><a href="#2">정수기렌탈</a></li>'
+'							<li><a href="#2">공기청정기/정수기</a></li>'
+'							<li><a href="#2">비데</a></li>'
+'							<li><a href="#2">전동칫솔/체중/혈압/체온계</a></li>'
+'							<li><a href="#2">안마기/마사지기</a></li>'
+'							<li><a href="#2">싸이클/운동기기</a></li>'
+'							<li><a href="#2">시계</a></li>'
+'						</ul></li>'
+'				</ul></li>'
+'			<li><a href="#2">DSLR/미러리스/디지털카메라</a>'
+'				<ul class="depth3">'
+'					<li><a href="#2">카메라/캠코더</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">DSLR카메라</a></li>'
+'							<li><a href="#2">컴팩트카메라</a></li>'
+'							<li><a href="#2">하이브리드카메라</a></li>'
+'							<li><a href="#2">인스탁스/토이카메라</a></li>'
+'							<li><a href="#2">캠코더</a></li>'
+'						</ul></li>'
+'					<li><a href="#2">DSLR카메라</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">캐논 DSLR</a></li>'
+'							<li><a href="#2">니콘 DSLR</a></li>'
+'							<li><a href="#2">소니 DSLR</a></li>'
+'						</ul></li>'
+'					<li><a href="#2">미러리스/하이브리드카메라</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">소니 미러리스</a></li>'
+'							<li><a href="#2">삼성 미러리스</a></li>'
+'							<li><a href="#2">캐논 미러리스</a></li>'
+'							<li><a href="#2">니콘 미러리스</a></li>'
+'							<li><a href="#2">삼성 스마트카메라</a></li>'
+'						</ul></li>'
+'					<li><a href="#2">카메라/캠코더 악세서리</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">삼각대</a></li>'
+'							<li><a href="#2">가방</a></li>'
+'							<li><a href="#2">SD/CF메모리카드</a></li>'
+'							<li><a href="#2">플래쉬</a></li>'
+'							<li><a href="#2">렌즈</a></li>'
+'							<li><a href="#2">카메라소품</a></li>'
+'							<li><a href="#2">쌍안경/망원경</a></li>'
+'							<li><a href="#2">캠코더소품</a></li>'
+'							<li><a href="#2">업링</a></li>'
+'							<li><a href="#2">디지털액자</a></li>'
+'						</ul></li>'
+'				</ul></li>'
+'			<li><a href="#2">태블릿PC/컴퓨터/주변기기</a>'
+'				<ul class="depth3">'
+'					<li><a href="#2">PC/데스크탑</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">데스크탑/일체형PC</a></li>'
+'							<li><a href="#2">애플-MAC</a></li>'
+'							<li><a href="#2">데스크탑-LG</a></li>'
+'							<li><a href="#2">데스크탑-삼성</a></li>'
+'							<li><a href="#2">데스크탑-HP/MONEUAL</a></li>'
+'							<li><a href="#2">데스크탑-LENOVO</a></li>'
+'							<li><a href="#2">데스크탑-DELL</a></li>'
+'							<li><a href="#2">데스크탑-ACER</a></li>'
+'							<li><a href="#2">일체형-LG</a></li>'
+'							<li><a href="#2">올인원PC-DELL</a></li>'
+'						</ul></li>'
+'					<li><a href="#2">노트북/테블릿</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">테블릿-넥서스</a></li>'
+'							<li><a href="#2">테블릿-ACER</a></li>'
+'							<li><a href="#2">테블릿-SONY</a></li>'
+'							<li><a href="#2">테블릿-ASUS</a></li>'
+'							<li><a href="#2">노트북-애플</a></li>'
+'							<li><a href="#2">노트북-LG</a></li>'
+'							<li><a href="#2">노트북-ACER</a></li>'
+'							<li><a href="#2">노트북-HP</a></li>'
+'							<li><a href="#2">노트북-LENOVO</a></li>'
+'							<li><a href="#2">노트북-ASUS</a></li>'
+'							<li><a href="#2">노트북-삼성</a></li>'
+'							<li><a href="#2">노트북-DELL</a></li>'
+'							<li><a href="#2">노트북-도시바</a></li>'
+'							<li><a href="#2">노트북-MSI</a></li>'
+'							<li><a href="#2">노트북-VAIO</a></li>'
+'							<li><a href="#2">기타-노트북/테블릿</a></li>'
+'						</ul></li>'
+'					<li><a href="#2">모니터/복합기/프린터/미니빔</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">모니터</a></li>'
+'							<li><a href="#2">LG 모니터</a></li>'
+'							<li><a href="#2">삼성 모니터</a></li>'
+'							<li><a href="#2">HMD</a></li>'
+'							<li><a href="#2">프린터</a></li>'
+'							<li><a href="#2">복합기</a></li>'
+'							<li><a href="#2">잉크</a></li>'
+'							<li><a href="#2">토너</a></li>'
+'							<li><a href="#2">미니빔</a></li>'
+'						</ul></li>'
+'					<li><a href="#2">키보드/마우스</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">키보드+마우스세트</a></li>'
+'							<li><a href="#2">유선키보드</a></li>'
+'							<li><a href="#2">무선키보드</a></li>'
+'							<li><a href="#2">유선마우스</a></li>'
+'							<li><a href="#2">무선마우스</a></li>'
+'							<li><a href="#2">블루투스마우스</a></li>'
+'							<li><a href="#2">마우스패드</a></li>'
+'						</ul></li>'
+'					<li><a href="#2">USB/외장하드/공CD</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">USB</a></li>'
+'							<li><a href="#2">외장하드</a></li>'
+'							<li><a href="#2">공CD</a></li>'
+'						</ul></li>'
+'					<li><a href="#2">공유기/네트워크</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">공유기</a></li>'
+'							<li><a href="#2">랜카드</a></li>'
+'							<li><a href="#2">허브</a></li>'
+'							<li><a href="#2">케이블</a></li>'
+'							<li><a href="#2">멀티탭</a></li>'
+'						</ul></li>'
+'					<li><a href="#2">스피커/헤드셋/이어셋</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">스피커</a></li>'
+'							<li><a href="#2">도킹스피커</a></li>'
+'							<li><a href="#2">헤드셋</a></li>'
+'							<li><a href="#2">이어셋</a></li>'
+'						</ul></li>'
+'					<li><a href="#2">노트북주변용품</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">노트북용가방/파우치</a></li>'
+'							<li><a href="#2">보안기(액정보호)</a></li>'
+'						</ul></li>'
+'					<li><a href="#2">컴퓨터주변기기</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">카드리더기</a></li>'
+'							<li><a href="#2">화상카메라</a></li>'
+'							<li><a href="#2">보안기</a></li>'
+'							<li><a href="#2">컴퓨터소품</a></li>'
+'						</ul></li>'
+'				</ul></li>'
+'			<li><a href="#2">게임기/네비게이션/MP3</a>'
+'				<ul class="depth3">'
+'					<li><a href="#2">네비게이션/하이패스</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">네비게이션</a></li>'
+'							<li><a href="#2">하이패스/블랙박스</a></li>'
+'						</ul></li>'
+'					<li><a href="#2">MP3/PMP/전자사전</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">애플-iPOD</a></li>'
+'							<li><a href="#2">MP3</a></li>'
+'							<li><a href="#2">PMP</a></li>'
+'							<li><a href="#2">어학학습기/전자사전</a></li>'
+'						</ul></li>'
+'					<li><a href="#2">오디오/라디오/이어폰</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">라디오/녹음기</a></li>'
+'							<li><a href="#2">이어폰</a></li>'
+'							<li><a href="#2">헤드폰</a></li>'
+'							<li><a href="#2">블루투스</a></li>'
+'							<li><a href="#2">오디오/카세트</a></li>'
+'						</ul></li>'
+'					<li><a href="#2">비디오게임기/게임</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">Wii</a></li>'
+'							<li><a href="#2">3DS/DSi</a></li>'
+'							<li><a href="#2">PS3/PSP Vita</a></li>'
+'							<li><a href="#2">XBOX</a></li>'
+'							<li><a href="#2">Wii 소프트웨어</a></li>'
+'							<li><a href="#2">3DS/DSi 소프트웨어</a></li>'
+'							<li><a href="#2">PS3/PSP Vita 소프트웨어</a></li>'
+'							<li><a href="#2">XBOX 소프트웨어</a></li>'
+'							<li><a href="#2">Wii 액세서리</a></li>'
+'							<li><a href="#2">3DS/DSi 액세서리</a></li>'
+'							<li><a href="#2">PS3/PSP Vita 액세서리</a></li>'
+'							<li><a href="#2">XBOX 액세서리</a></li>'
+'							<li><a href="#2">PC게임</a></li>'
+'						</ul></li>'
+'				</ul></li>'
+'			<li><a href="#2">리디북스 e-Book</a>'
+'				<ul class="depth3">'
+'					<li><a href="#2">태블릿+e-Book</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">넥서스+e-Book</a></li>'
+'							<li><a href="#2">아이패드+e-Book</a></li>'
+'							<li><a href="#2">아이패드미니+e-Book</a></li>'
+'						</ul></li>'
+'					<li><a href="#2">e-Book</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">e-Book</a></li>'
+'						</ul></li>'
+'				</ul></li>'
+'			<li><a href="#2">테블릿PC/스마트폰악세서리</a>'
+'				<ul class="depth3">'
+'					<li><a href="#2">아이패드</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">아이패드케이스</a></li>'
+'							<li><a href="#2">아이패드보호필름</a></li>'
+'						</ul></li>'
+'					<li><a href="#2">갤럭시S</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">갤럭시S케이스</a></li>'
+'							<li><a href="#2">캘럭시S보호필름</a></li>'
+'						</ul></li>'
+'					<li><a href="#2">아이폰</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">아이폰케이스</a></li>'
+'							<li><a href="#2">아이폰보호필름</a></li>'
+'						</ul></li>'
+'					<li><a href="#2">갤럭시노트</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">갤럭시노트케이스</a></li>'
+'							<li><a href="#2">갤럭시노트보호필름</a></li>'
+'						</ul></li>'
+'					<li><a href="#2">넥서스7/기타휴대폰</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">휴대폰케이스</a></li>'
+'							<li><a href="#2">휴대폰보호필름</a></li>'
+'							<li><a href="#2">넥서스7케이스/보호필름</a></li>'
+'						</ul></li>'
+'					<li><a href="#2">스트랩/블루투스/기타</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">스트랩</a></li>'
+'							<li><a href="#2">블루투스</a></li>'
+'							<li><a href="#2">거치대/악세서리</a></li>'
+'							<li><a href="#2">테블릿 PC 키보드/기타</a></li>'
+'						</ul></li>'
+'					<li><a href="#2">이어폰/충전기</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">이어폰</a></li>'
+'							<li><a href="#2">헤드폰</a></li>'
+'							<li><a href="#2">충전기/케이블</a></li>'
+'						</ul></li>'
+'				</ul></li>'
+'			<li><a href="#2">생활/건강가전</a>'
+'				<ul class="depth3">'
+'					<li><a href="#2">면도기</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">면도기</a></li>'
+'							<li><a href="#2">면도기악세서리</a></li>'
+'						</ul></li>'
+'					<li><a href="#2">드라이어/고데기/피부미용</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">드라이어</a></li>'
+'							<li><a href="#2">고데기</a></li>'
+'							<li><a href="#2">피부미용</a></li>'
+'						</ul></li>'
+'					<li><a href="#2">청소기</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">일반형청소기</a></li>'
+'							<li><a href="#2">로봇청소기</a></li>'
+'							<li><a href="#2">핸디형/스틱형청소기</a></li>'
+'							<li><a href="#2">침구청소기</a></li>'
+'							<li><a href="#2">업소용청소기</a></li>'
+'							<li><a href="#2">스팀청소기</a></li>'
+'							<li><a href="#2">청소기소품</a></li>'
+'						</ul></li>'
+'					<li><a href="#2">전화기/온수기/생활가전</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">다리미/미싱</a></li>'
+'							<li><a href="#2">체온계/전동칫솔/전자담배</a></li>'
+'							<li><a href="#2">유선/유무선전화기</a></li>'
+'							<li><a href="#2">전기온수기/저장식온수기</a></li>'
+'							<li><a href="#2">비데/전자식비데</a></li>'
+'						</ul></li>'
+'					<li><a href="#2">안마의자/건강가전</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">안마의자</a></li>'
+'							<li><a href="#2">안마기/마사지기</a></li>'
+'							<li><a href="#2">찜질기/찜질팩/매트</a></li>'
+'							<li><a href="#2">건강측정용품</a></li>'
+'							<li><a href="#2">건강용품</a></li>'
+'						</ul></li>'
+'				</ul></li>'
+'			<li><a href="#2">TV/냉장고/세탁기/AV-음향가전</a>'
+'				<ul class="depth3">'
+'					<li><a href="#2">3D,LEDTV/LCD/PDP</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">PDPTV</a></li>'
+'							<li><a href="#2">LCDTV</a></li>'
+'							<li><a href="#2">LEDTV</a></li>'
+'							<li><a href="#2">TV악세서리</a></li>'
+'							<li><a href="#2">TV리모컨</a></li>'
+'							<li><a href="#2">TV장식장</a></li>'
+'						</ul></li>'
+'					<li><a href="#2">냉장고/김치냉장고</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">양문형냉장고</a></li>'
+'							<li><a href="#2">냉장고</a></li>'
+'							<li><a href="#2">기능성냉장고</a></li>'
+'							<li><a href="#2">뚜껑식김치냉장고</a></li>'
+'							<li><a href="#2">스탠드형김치냉장고</a></li>'
+'							<li><a href="#2">냉동고</a></li>'
+'							<li><a href="#2">와인셀러</a></li>'
+'						</ul></li>'
+'					<li><a href="#2">세탁기/드럼세탁기/건조기</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">세탁기</a></li>'
+'							<li><a href="#2">드럼세탁기</a></li>'
+'							<li><a href="#2">의류건조기</a></li>'
+'							<li><a href="#2">의류관리기</a></li>'
+'						</ul></li>'
+'					<li><a href="#2">AV-음향가전</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">홈시어터</a></li>'
+'							<li><a href="#2">블루레이플레이어</a></li>'
+'							<li><a href="#2">DVD플레이어</a></li>'
+'							<li><a href="#2">오디오</a></li>'
+'						</ul></li>'
+'				</ul></li>'
+'			<li><a href="#2">CCTV/도어락/인터폰/금고</a>'
+'				<ul class="depth3">'
+'					<li><a href="#2">CCTV</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">DVR</a></li>'
+'							<li><a href="#2">카메라</a></li>'
+'							<li><a href="#2">주변기기</a></li>'
+'						</ul></li>'
+'					<li><a href="#2">디지털 도어락</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">주키</a></li>'
+'							<li><a href="#2">보조키</a></li>'
+'						</ul></li>'
+'					<li><a href="#2">인터폰</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">도어폰</a></li>'
+'							<li><a href="#2">인터폰</a></li>'
+'						</ul></li>'
+'					<li><a href="#2">비디오폰</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">COLOR</a></li>'
+'							<li><a href="#2">B/W</a></li>'
+'						</ul></li>'
+'					<li><a href="#2">금고</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">가정용</a></li>'
+'							<li><a href="#2">산업용</a></li>'
+'						</ul></li>'
+'					<li><a href="#2">방범/화재</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">방범센서</a></li>'
+'							<li><a href="#2">화재센서</a></li>'
+'						</ul></li>'
+'					<li><a href="#2">비상/호신용품</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">LED렌턴</a></li>'
+'							<li><a href="#2">비상용품</a></li>'
+'							<li><a href="#2">호신용품</a></li>'
+'						</ul></li>'
+'				</ul></li>'
+'			<li><a href="#2">주방가전/주방소형</a>'
+'				<ul class="depth3">'
+'					<li><a href="#2">전기압력밥솥/전기밥솥/일반압력솥</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">전기압력밥솥/압력밥솥</a></li>'
+'							<li><a href="#2">IH압력밥솥</a></li>'
+'						</ul></li>'
+'					<li><a href="#2">가스/오븐/전자레인지</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">가스레인지</a></li>'
+'							<li><a href="#2">가스오븐레인지</a></li>'
+'							<li><a href="#2">전자레인지</a></li>'
+'							<li><a href="#2">전기레인지</a></li>'
+'							<li><a href="#2">광파오븐레인지</a></li>'
+'							<li><a href="#2">스마트오븐</a></li>'
+'						</ul></li>'
+'					<li><a href="#2">커피메이커/주전자/토스터기</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">커피메이커</a></li>'
+'							<li><a href="#2">커피머신</a></li>'
+'							<li><a href="#2">주전자-전기포트/라면포트</a></li>'
+'							<li><a href="#2">토스터기</a></li>'
+'						</ul></li>'
+'					<li><a href="#2">녹즙기/믹서기</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">녹즙기/쥬서기</a></li>'
+'							<li><a href="#2">믹서기</a></li>'
+'							<li><a href="#2">핸드블랜더</a></li>'
+'							<li><a href="#2">약탕기/중탕기</a></li>'
+'						</ul></li>'
+'					<li><a href="#2">식기세척기/건조기/음식물처리기</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">식기세척기</a></li>'
+'							<li><a href="#2">건조기</a></li>'
+'							<li><a href="#2">음식물처리기</a></li>'
+'						</ul></li>'
+'					<li><a href="#2">전기그릴/전기팬/튀김기</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">전기그릴</a></li>'
+'							<li><a href="#2">전기팬</a></li>'
+'							<li><a href="#2">튀김기</a></li>'
+'							<li><a href="#2">에어프라이어</a></li>'
+'						</ul></li>'
+'				</ul></li>'
+'			<li><a href="#2">에어컨/제습기/선풍기	</a>'
+'				<ul class="depth3">'
+'					<li><a href="#2">에어컨</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">에어컨-3in1</a></li>'
+'							<li><a href="#2">에어컨-2in1</a></li>'
+'							<li><a href="#2">에어컨-스탠드형</a></li>'
+'							<li><a href="#2">에어컨-벽걸이형</a></li>'
+'						</ul></li>'
+'					<li><a href="#2">선풍기</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">선풍기</a></li>'
+'							<li><a href="#2">벽걸이선풍기</a></li>'
+'						</ul></li>'
+'					<li><a href="#2">제습기</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">제습기</a></li>'
+'						</ul></li>'
+'					<li><a href="#2">가습기/에어워셔</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">에어워셔</a></li>'
+'							<li><a href="#2">복합기/가열식</a></li>'
+'							<li><a href="#2">살균기</a></li>'
+'						</ul></li>'
+'				</ul></li></ul></li>'
+'	<li class="menu2_4"><a href="#1"><span>툥큰.손큰/PB</span></a>'
+'		<ul class="depth2" style="display:none;">'
+'			<li><a href="#2">통큰.손큰</a>'
+'			</li>'
+'			<li><a href="#2">PB</a>'
+'				<ul class="depth3">'
+'					<li><a href="#2">건강한 FOOD</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">과자/대용식/냉장냉동</a></li>'
+'							<li><a href="#2">친환경식품</a></li>'
+'							<li><a href="#2">커피차/음료/유제품/잼</a></li>'
+'							<li><a href="#2">과일/채소/쌀/견과</a></li>'
+'							<li><a href="#2">조미료/통조림</a></li>'
+'							<li><a href="#2">소고기/돼지고기/닭고기/계란</a></li>'
+'							<li><a href="#2">간편 가정식</a></li>'
+'							<li><a href="#2">생선/건해산물</a></li>'
+'						</ul></li>'
+'					<li><a href="#2">행복한 LIFE</a>'
+'						<ul class="depth4">'
+'							<li><a href="#2">바디/헤어/미용</a></li>'
+'							<li><a href="#2">애완/애견용품</a></li>'
+'							<li><a href="#2">화장지/욕실/세제</a></li>'
+'							<li><a href="#2">가전/디지털</a></li>'
+'							<li><a href="#2">스포츠/레저/자동차</a></li>'
+'							<li><a href="#2">가정용품</a></li>'
+'							<li><a href="#2">문구/오피스</a></li>'
+'							<li><a href="#2">패션의류/잡화 주방용품</a></li>'
+'						</ul></li>'
+'				</ul></li></ul></li>'
+'	<li class="menu2_5"><a href="#5"><span>기획전</span></a></li>'
+'	<li class="menu2_6"><a href="#6"><span>HOT 이벤트</span></a></li>'
+'	<li class="menu2_7"><a href="#7"><span>쿠폰존</span></a></li>'
+'	<li class="menu2_8"><a href="#7"><span>전문관</span></a></li>'
+'	<li class="menu2_9"><a href="#7"><span>요리왕 장보고</span></a></li>'
+'</ul>';

document.write( _ux_category );
